### PR TITLE
Validate Guides

### PR DESCRIPTION
**Pull request by RevGear**
Feel free to ditch this one if you think it not appropriate or could be done better.

Now that the legacy guides has been disabled it's highlighted a problem that I've been meaning to look at for a while. There are channels where we have data in the legacy guides but for whatever reason that channel is not being picked up in the combined guides. I suspect in many cases it may be a mis-match between the EPG language and the expected language(s) for the broadcast region. The first step will be to identify which channels are not being included in the combined guides, which is the point of this PR.

Run as guides:validate
It loops through the channel API, checks if there are any entries in the programs database, then checks the guide API.

```
┌─────────┬────────────┬────────────────────────┬─────────────────────────┬─────────┐
│ (index) │    type    │        xmltv_id        │          name           │ country │
├─────────┼────────────┼────────────────────────┼─────────────────────────┼─────────┤
│    0    │ 'no_guide' │    'APlusKidsTV.uk'    │      'A+ Kids TV'       │  'UK'   │
│    1    │ 'no_guide' │  'DorcelTVAfrica.nl'   │   'Dorcel TV Africa'    │  'NL'   │
│    2    │ 'no_guide' │   'Elmouritania.mr'    │     'Elmouritania'      │  'MR'   │
│    3    │ 'no_guide' │     'FarinWata.ng'     │      'Farin Wata'       │  'NG'   │
│    4    │ 'no_guide' │   'I24NewsFrench.il'   │    'I24 News French'    │  'IL'   │
│    5    │ 'no_guide' │ 'IqraaAfricaEurope.sa' │ 'Iqraa Africa & Europe' │  'SA'   │
│    6    │ 'no_guide' │   'Medi1TVArabic.ma'   │   'Medi 1 TV Arabic'    │  'MA'   │
│    7    │ 'no_guide' │      'SunnaTV.ng'      │       'Sunna TV'        │  'NG'   │
│    8    │ 'no_guide' │        'TGB.gw'        │          'TGB'          │  'GW'   │
│    9    │ 'no_guide' │     'VoxAfrica.uk'     │       'VoxAfrica'       │  'UK'   │
└─────────┴────────────┴────────────────────────┴─────────────────────────┴─────────┘
```
My thinking was to add a workflow to do this daily, or maybe add to the _update workflow.

Sorry if this is a bit long but one quick question to add. It was mentioned previously that the ideal plan would be to create an EPG that showed the program details in multiple languages. Longer term, is that still the plan?

### CODE REVIEW

**Comment by freearhey** [comment]
> Now that the legacy guides has been disabled it's highlighted a problem that I've been meaning to look at for a while. There are channels where we have data in the legacy guides but for whatever reason that channel is not being picked up in the combined guides. I suspect in many cases it may be a mis-match between the EPG language and the expected language(s) for the broadcast region. The first step will be to identify which channels are not being included in the combined guides, which is the point of this PR.

Totally agree with all of the above and the solution seems reasonable to me. 

The only thing about the script I would replace [api.guides](https://github.com/iptv-org/epg/pull/1623/commits/f21ae7f6462e1b93d8af1a4a5166b7d1585dbc6e#diff-9e3ffd810bca903e988682dd4f5a656e396dfcc307ea3b9ce179d91944fcc749R6) with [logs/guides/update.log](https://github.com/iptv-org/epg/pull/1623/files#diff-9e3ffd810bca903e988682dd4f5a656e396dfcc307ea3b9ce179d91944fcc749R11-R13) which is filled with each update:
 https://github.com/iptv-org/epg/blob/59ef72997864ac9df63c181f5d8ba39ecfc9c3f8/scripts/commands/guides/update.js#L124-L134
That way we don't have to wait for the API to update before running the check.

To make it easier to debug this log now be also available to download as an artifact: https://github.com/iptv-org/epg/commit/59ef72997864ac9df63c181f5d8ba39ecfc9c3f8

The rest of the changes:

- added a few more fields to the output to make it easier to understand what doesn't add up

```sh
┌─────────┬────────────┬─────────────────────────┬──────┬────────────────────────┬────────────────┬──────────────────┐
│ (index) │    type    │          site           │ lang │        xmltv_id        │ broadcast_area │    languages     │
├─────────┼────────────┼─────────────────────────┼──────┼────────────────────────┼────────────────┼──────────────────┤
│    0    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │    'APlusKidsTV.uk'    │   [ 'c/UK' ]   │    [ 'eng' ]     │
│    1    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │     'VoxAfrica.uk'     │   [ 'c/UK' ]   │ [ 'fra', 'eng' ] │
│    2    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │   'Elmouritania.mr'    │   [ 'c/MR' ]   │    [ 'ara' ]     │
│    3    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │   'I24NewsFrench.il'   │   [ 'c/IL' ]   │    [ 'fra' ]     │
│    4    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │  'DorcelTVAfrica.nl'   │   [ 'c/NL' ]   │    [ 'fra' ]     │
│    5    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │ 'IqraaAfricaEurope.sa' │   [ 'c/SA' ]   │ [ 'fra', 'eng' ] │
│    6    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │      'SunnaTV.ng'      │   [ 'c/NG' ]   │    [ 'eng' ]     │
│    7    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │        'TGB.gw'        │   [ 'c/GW' ]   │    [ 'fra' ]     │
│    8    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │   'Medi1TVArabic.ma'   │   [ 'c/MA' ]   │    [ 'ara' ]     │
│    9    │ 'no_guide' │ 'canalplus-afrique.com' │ 'fr' │     'FarinWata.ng'     │   [ 'c/NG' ]   │    [ 'eng' ]     │
└─────────┴────────────┴─────────────────────────┴──────┴────────────────────────┴────────────────┴──────────────────┘
```

- added a `guides/validate.test.js`
- added a script to `_update.yml`

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
As for multiple languages in the program description, I'm all for it, but until most popular players will not add support for such guides, I do not know what we can do here.

**Comment by RevGear** [comment]
> As for multiple languages in the program description, I'm all for it, but until most popular players will not add support for such guides, I do not know what we can do here.

From what I've read Tivimate doesn't give the option to select which language to use but will automatically use the default system language if that's one of the options available. That doesn't appear to be widely documented, and I don't know if other players will do the same.

Would it be possible to create 2 version of each guides - the current one and then a multi-language version. That way those who can support it get the benefit and it doesn't break anything for those that can't

**Comment by freearhey** [comment]
After testing with real data, it turned out that during the check most of the time is consumed by loading the file `database/programs.db` (over [630Mb](https://github.com/iptv-org/epg/actions/runs/3866356183)), so I decided to move the check to the file [guides/update.js](https://github.com/iptv-org/epg/pull/1623/files#diff-2fd4cf4012fa543c95f1fe7f608cc507539f1a9d84cd012a40973c2cbdc5a0acR186-R201) where this file is already loaded.

**Comment by freearhey** [comment]
> Tivimate doesn't give the option to select which language to use but will automatically use the default system language if that's one of the options available

So if the system language is for example Romanian and the guide is in English, then for the user this guide will be empty? And what will users see in other applications?

This is all solvable of course, but experience shows that users will not go to the developers of the app with these issues, but will come here. This is why I don't want to make a separate version of the guide for any particular app. But if such guides ever get wide support, we will definitely switch to them.

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Here are the first results:

https://github.com/iptv-org/epg/actions/runs/3866899892/jobs/6591321099

(tab "Run npm run guides:update" at the very bottom)

But it may even be too much data for this console:

image

**Comment by RevGear** [comment]
> Here are the first results:
> 
> https://github.com/iptv-org/epg/actions/runs/3866899892/jobs/6591321099

That's more than I was expecting, although there is some duplication of the channel being in two sources and neither being used. Gives us something to work with at least.

**Pull request merged**
