### PR TITLE
[Fix] ziggogo.tv

### PR DESCRIPTION
**Pull request by BellezaEmporium**
- New endpoints used in Ziggo, old endpoints still work, but for safety measures these are changed to fit what's being used currently. The program details didn't seem to load using Axios, using Node's native fetch for that.
- Tests have been updated.
- Test data has been updated.

Closes https://github.com/iptv-org/epg/issues/2393

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```sh
npm test --- ziggogo.tv

> test
> run-script-os ziggogo.tv


> test:default
> TZ=Pacific/Nauru npx jest --runInBand ziggogo.tv

 FAIL  sites/ziggogo.tv/ziggogo.tv.test.js (13.284 s)
  ✓ can generate valid url (6 ms)
  ✕ can parse response (10002 ms)
  ✓ can handle empty guide (2 ms)

  ● can parse response

    thrown: "Exceeded timeout of 10000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      24 | })
      25 |
    > 26 | it('can parse response', async () => {
         | ^
      27 |   const content = fs.readFileSync(path.resolve(__dirname, '__data__/content_0000.json'))
      28 |
      29 |   axios.get.mockImplementation(url => {

      at Object.<anonymous> (sites/ziggogo.tv/ziggogo.tv.test.js:26:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        13.498 s
Ran all test suites matching /ziggogo.tv/i.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by BellezaEmporium** [comment]
Will check.

**Comment by tohenk** [comment]
This site is similar with [sites/virgintvgo.virginmedia.com](https://github.com/iptv-org/epg/tree/master/sites/virgintvgo.virginmedia.com) i've just worked a while ago.

**Comment by BellezaEmporium** [comment]
I'm quite sure your method would also work on ziggogo.tv.

**Comment by tohenk** [comment]
```sh
npm test --- ziggogo.tv

> test
> run-script-os ziggogo.tv


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand ziggogo.tv

 PASS  sites/ziggogo.tv/ziggogo.tv.test.js
  √ can generate valid url (5 ms)
  √ can parse response (1040 ms)
  √ can handle empty guide (3 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        4.767 s, estimated 8 s
Ran all test suites matching /ziggogo.tv/i.
```

**Comment by BellezaEmporium** [comment]
Nice work @tohenk !

**Review by freearhey — APPROVED** [review]

**Comment by PopeyeTheSai10r** [comment]
Test failed

```
npm test --- ziggogo.tv

> test
> run-script-os ziggogo.tv


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand ziggogo.tv

 FAIL  sites/ziggogo.tv/ziggogo.tv.test.js
  ● Test suite failed to run

    Cannot find module '@ntlab/sfetch' from 'sites/ziggogo.tv/ziggogo.tv.config.js'

    Require stack:
      sites/ziggogo.tv/ziggogo.tv.config.js
      sites/ziggogo.tv/ziggogo.tv.test.js

      1 | const dayjs = require('dayjs')
      2 | const utc = require('dayjs/plugin/utc')
    > 3 | const doFetch = require('@ntlab/sfetch')
        |                 ^
      4 | const debug = require('debug')('site:ziggogo.tv')
      5 |
      6 | dayjs.extend(utc)

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (sites/ziggogo.tv/ziggogo.tv.config.js:3:17)
      at Object.<anonymous> (sites/ziggogo.tv/ziggogo.tv.test.js:1:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        13.553 s
Ran all test suites matching `/ziggogo.tv/i.
```

**Comment by tohenk** [comment]
@PopeyeTheSai10r , do `npm install` or `npm update` first as it depends on the new `@ntlab/sfetch` package.

**Comment by PopeyeTheSai10r** [comment]
All tests passed when running `npm install` followed by `npm test --- ziggogo.tv`

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
