### PR TITLE
Re-added History Channel after api update

### PR DESCRIPTION
**Pull request by Dexer125**

### CODE REVIEW

**Review by Shoang1123344 — APPROVED** [review]
Z7hCHDkEJuUN7TT

**Comment by PopeyeTheSai10r** [comment]
The check failed because **HistoryHDCzechRepublic.cz** is not a valid TVG-ID.

**Comment by Dexer125** [comment]
> The check failed because **HistoryHDCzechRepublic.cz** is not a valid TVG-ID.

Yep, I added that to channels.csv but made one mistake in PR. Unfortunately I can't fix it as I don't have my PC now.

**Comment by Dexer125** [comment]
> The check failed because **HistoryHDCzechRepublic.cz** is not a valid TVG-ID.

It merged in database. Now it can be merged here.

**Comment by PopeyeTheSai10r** [comment]
The check failed because **KETV.kr** is not a valid TVG-ID.

**Comment by Dexer125** [comment]
> The check failed because **KETV.kr** is not a valid TVG-ID.

If you open that check, you can see that it was not check for m.tv.sms.cz. None of those channels from failed ones are not present in xml for m.tv.sms.cz

**Review by freearhey — APPROVED** [review]

**Pull request merged**
