### PR TITLE
Add orangetv.es provider

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
I made the code based on a proposal from @fraudiay79 in [this thread](https://github.com/iptv-org/epg/issues/2466#issuecomment-2493938738).
I've made some improvements and made sure the code performs at a basic level.

Currently this PR is NOT ready to be merged. I've made it in order to get valuable feedback and maybe get some help with it.
I've made some tests but these are not ready for prime time, some API mocking needs to be implemented for that.

Furthermore the channels list needs to be cleaned up, since some channels appear as available but don't have any programs available.
Also the possibility exists that there is still some glaring issue in the code I've looked over.

@BellezaEmporium @PopeyeTheSai10r Would you be willing to have a look at it in order to provide some feedback?

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
Seems like you've got inspired from the telenet.tv website. A few quacks on my side that i'm solving.

**Comment by davidclaeysquinones** [comment]
> '

yeah I took some inspiration from that and the pick.be provider.

**Comment by BellezaEmporium** [comment]
Managed to get the programs. The tests aren't working yet xd

**Comment by davidclaeysquinones** [comment]
> Managed to get the programs. The tests aren't working yet xd
> 
> image

Was the program retrieval broken ?

**Comment by davidclaeysquinones** [comment]
Btw thanks for helping out with the tests.

**Comment by BellezaEmporium** [comment]
> > Managed to get the programs. The tests aren't working yet xd
> > image
> 
> Was the program retrieval broken ?

I had an error message about dayjs.utc. It was because you didn't import it on the code.

```
const utc = require('dayjs/plugin/utc')

dayjs.extend(utc)
```

was necessary in order for the code to work.

**Comment by davidclaeysquinones** [comment]
That's weird since I have it working. I might have made a copy paste error.
Anyway I've seen you've made some nice improvements.

**Comment by davidclaeysquinones** [comment]
However I'm afraid there might be some duplicate ítems in the program array. Tbh the way it's made is quite inefficient.

A first requests is send to an URL, and aftherwards 3 more requests are send. 
That first request is Made because the framework expects an URL to retrieve the content from.
But actually only the 3 requests are really usefull.

**Comment by BellezaEmporium** [comment]
Well, on my side, the code works quite well. The EPG looks good on my side, though there's one single test failing. I've managed to fix one, though one test is failing.

**Comment by BellezaEmporium** [comment]
Works fine on my watch now, both programs and tests.

**Comment by BellezaEmporium** [comment]
I'll let everyone test the current code as-is, and if it becomes positive, @davidclaeysquinones you'll be free to make it R2R.

**Comment by BellezaEmporium** [comment]
By the way, I see that #TODO in readme contains this : 

```
### Todo

Some channels of this provider are not added to the channel database :

- RuntimeSeries.es
- RuntimeCineSeries.es
- RuntimeCineTerror.es
- RuntimeAccion.es
- RuntimeComedia.es
- RuntimeCrimen.es
- RuntimeRomance.es
- RunTimeClasico.es
- CinesVerdiTV.es
- CineFeelGood.es
- Gametoon.es
```

The Runtime channels are FAST channels. They can be categorised the same as the Pluto.tv ones.
A few local channels aren't in the database as well, like "Castello TV (Televisio Castello ?)" and "Navarra TV 2".
I suggest to add those local ones, as they can be added later on if we stumble upon them in streams.

https://www.navarratelevision.es/AppParrilla.aspx?canal=Canal2
https://kick.com/televisiocastello

**Comment by davidclaeysquinones** [comment]
I forgot about that issue but there were quite some channels where I didn't know what I should do with them.

The Gametoon one seemed weird because I doubted they were going to transmit a dutch channel in Spain.
And I had no idea about the Runtine/Fast channels being the same as the Pluto channels.

The channel grabber spit outs also a bunch of other channels, but there is not programs to be found  for them.
So I opted to leaving them out.

I suspect depending on the region they put the local channels in a dedicated feed.

**Comment by davidclaeysquinones** [comment]
I've updated some runtime channels although I haven't found an alternative for all of them.

**Comment by BellezaEmporium** [comment]
I see what you've did, though I think there was a confusion.

When I meant that "Runtime channels can be classified the same as Pluto.tv channels", I meant that since the Pluto TV channels exist, there's a place to add Runtime channels in the database.

Actually, we do have 2 Runtime channels available.

**Comment by BellezaEmporium** [comment]
I see what you've did, though I think there was a confusion.

When I meant that "Runtime channels can be classified the same as Pluto.tv channels", I meant that since the Pluto TV channels exist, there's a place to add Runtime channels in the database.

Actually, we do have 2 Runtime channels available.

**Comment by davidclaeysquinones** [comment]
That was was pretty stupid of me.
I'll add it to the database file.

I've received the advice to use a bot to do it but I have no clue.

**Comment by davidclaeysquinones** [comment]
I have made a [PR](https://github.com/iptv-org/database/pull/14988) with the additional channels

**Review by freearhey — CHANGES_REQUESTED** [review]
Please replace `orangetv.es` with the real domain `orangetv.orange.es`.

**Comment by davidclaeysquinones** [comment]
> Please replace `orangetv.es` with the real domain `orangetv.orange.es`.

I renamed the provider to the real domain

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
