### PR TITLE
Update mi.tv

### PR DESCRIPTION
**Pull request by freearhey**
Added guides for:

- Argentine
- Chile
- Colombia
- El Salvador
- Guatemala
- Honduras
- Mexico
- Paraguay
- Peru

### CODE REVIEW

**Review by Dum4G — APPROVED** [review]

**Comment by Dum4G** [comment]
At IPTV repo we are not supposed to do blind approves and we usually don't. Why do we have that limitation here of you're the only contributor and members are... trustful people?

**Comment by LaneSh4d0w** [comment]
Arhey tends to test his scripts before actually making it ready for review. I often approve because I am confident about his work.

If there's some things to fix that are told or that we spotted, it'll be fixed on due time.

**Comment by Dum4G** [comment]
Thing is - you're the only one who can even theoretically review quality of his job. I'm not JS enthusiast at all

**Comment by LaneSh4d0w** [comment]
> 
> 
> Thing is - you're the only one who can even theoretically review quality of his job. I'm not JS enthusiast at all

If you wanna review this kind of work, simply take a look at the HTML DOM page of the website he's scraping and look at the possible differences you could spot.

**Comment by freearhey** [comment]
Please do not approve changes if you cannot verify them. 

I am asking for a review precisely so that someone else can make sure that everything works as it should. If you cannot currently test the code, please ignore the request.

@Dum4G My mistake, I will no longer send you a request from this repository.

**Pull request merged**
