### PR TITLE
Add guide from tvguide.com

### LINKED ISSUE #50: Use tvguide.com for USA EPG
Can you use the "tvguide.com" site for the USA EPG, and would show the schedule from 6am on one day to 6am on next day?

### PR DESCRIPTION
**Pull request by freearhey**
Resolves #50

### CODE REVIEW

**Review by LaneSh4d0w — APPROVED** [review]

**Comment by Philblue7** [comment]
Can the guide be used instead of tvtv.us? There's no tvguide.com.guide.xml.

**Comment by freearhey** [comment]
@Philblue7 The program guide from tvguide.com is now available at `https://iptv-org.github.io/epg/guides/tvguide.com.guide.xml`

The main program for US will remain `tvtv.us`, simply because it currently has more channels and more info about each program.

**Comment by Philblue7** [comment]
Also, could all the guides show what's on for two weeks?

**Comment by freearhey** [comment]
No, it is not possible simply because not all sources contain programs even for 3 days in advance.

**Comment by Philblue7** [comment]
Is there an EPG that has Kabillion's over-the-top schedule?

**Comment by freearhey** [comment]
I don't know.

**Comment by Philblue7** [comment]
Some of the networks like ABC, CBS, The CW, Fox, and PBS Kids are missing from the channels.

**Comment by freearhey** [comment]
Feel free to add the missing channels yourself: https://github.com/iptv-org/epg/blob/master/sites/tvguide.com.channels.xml

**Comment by freearhey** [comment]
No, I don't have time for that.

**Pull request merged**
