### PR TITLE
Add guide from mncvision.id

### LINKED ISSUE #20: Mncvision
can you add the epg from this site https://www.mncvision.id/schedule

### PR DESCRIPTION
**Pull request by freearhey**
Resolves #20

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
It was painful fixing the package-lock.json file by hand. Maybe it'll need a rewrite from npm.

**Comment by kyliezero** [comment]
#there is something missing
`Infotainment Channel 96`
<channel lang="id" xmltv_id="Infotainment.id" site_id="96">Infotainment</channel>

**Comment by freearhey** [comment]
@kyliezero Thanks! Added to the list via https://github.com/iptv-org/epg/commit/92b64f4d1639fa036c37dd6a3f64c63d56e8eac7

**Comment by kyliezero** [comment]
> @kyliezero Thanks! Added to the list via [92b64f4](https://github.com/iptv-org/epg/commit/92b64f4d1639fa036c37dd6a3f64c63d56e8eac7)

Thank you in advance for your response about my input, maybe you can add a description of the channel schedule
Screenshot_2021-11-12-01-47-53-294_com android chrome

**Pull request merged**
