### PR TITLE
Add program icons to Telenet.Tv icons

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
This PR adds program icons to the Telenet.tv provider.

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```sh
npm test -- telenet.tv      

> test
> run-script-os telenet.tv


> test:default
> TZ=Pacific/Nauru npx jest --runInBand telenet.tv

 FAIL  sites/telenet.tv/telenet.tv.test.js
  ✓ can generate valid url (18 ms)
  ✕ can parse response (58 ms)
  ✓ can handle empty guide (1 ms)

  ● can parse response

    expect(received).toMatchObject(expected)

    - Expected  - 17
    + Received  +  5

      Object {
    -   "actors": Array [
    -     "Gale Harold",
    -     "Hal Sparks",
    -     "Randy Harrison",
    -     "Peter Paige",
    -     "Scott Lowell",
    -     "Thea Gill",
    -     "Michelle Clunie",
    -     "Sharon Gless",
    -   ],
    -   "category": Array [
    -     "Dramaserie",
    -     "LHBTI",
    -   ],
    -   "description": "Justin belandt in de gevangenis, Brian en Brandon banen zich een weg door de lijst, Ben treurt, Melanie en Lindsay proberen een interne scheiding en Emmett's stalker onthult zichzelf.",
    -   "episode": 8,
    -   "season": 5,
    +   "actors": undefined,
    +   "category": undefined,
    +   "description": undefined,
    +   "episode": null,
    +   "season": null,
        "start": "2022-10-29T23:56:00.000Z",
        "stop": "2022-10-30T01:44:00.000Z",
        "title": "Queer as Folk USA",
      }

      60 |   })
      61 |
    > 62 |   expect(results[0]).toMatchObject({
         |                      ^
      63 |     start: '2022-10-29T23:56:00.000Z',
      64 |     stop: '2022-10-30T01:44:00.000Z',
      65 |     title: 'Queer as Folk USA',

      at Object.<anonymous> (sites/telenet.tv/telenet.tv.test.js:62:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        3.81 s
Ran all test suites matching /telenet.tv/i.
```

**Comment by davidclaeysquinones** [comment]
I'll have a look at why the test fails and try to solve it

**Comment by PopeyeTheSai10r** [comment]
Test failed:

<details>
  <summary>Output</summary>
 
```
run-script-os telenet.tv


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand telenet.tv

 FAIL  sites/telenet.tv/telenet.tv.test.js (10.318 s)
  √ can generate valid url (15 ms)
  × can parse response (150 ms)
  √ can handle empty guide (3 ms)

  ● can parse response

    expect(received).toMatchObject(expected)

    - Expected  - 17
    + Received  +  5

      Object {
    -   "actors": Array [
    -     "Gale Harold",
    -     "Hal Sparks",
    -     "Randy Harrison",
    -     "Peter Paige",
    -     "Scott Lowell",
    -     "Thea Gill",
    -     "Michelle Clunie",
    -     "Sharon Gless",
    -   ],
    -   "category": Array [
    -     "Dramaserie",
    -     "LHBTI",
    -   ],
    -   "description": "Justin belandt in de gevangenis, Brian en Brandon banen zich een weg door de lijst, Ben treurt, Melanie en Lindsay proberen een interne scheiding en Emmett's stalker onthult zichzelf.",
    -   "episode": 8,
    -   "season": 5,
    +   "actors": undefined,
    +   "category": undefined,
    +   "description": undefined,
    +   "episode": null,
    +   "season": null,
        "start": "2022-10-29T23:56:00.000Z",
        "stop": "2022-10-30T01:44:00.000Z",
        "title": "Queer as Folk USA",
      }

      60 |   })
      61 |
    > 62 |   expect(results[0]).toMatchObject({
         |                      ^
      63 |     start: '2022-10-29T23:56:00.000Z',
      64 |     stop: '2022-10-30T01:44:00.000Z',
      65 |     title: 'Queer as Folk USA',

      at Object.<anonymous> (sites/telenet.tv/telenet.tv.test.js:62:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        10.991 s, estimated 13 s
Ran all test suites matching /telenet.tv/i.

```
</details>

**Comment by davidclaeysquinones** [comment]
I've been doing some tests and found out that the test for this provider is just broken.
Even if you perform the test on the release code it fails.
I'll try to fix it

**Comment by davidclaeysquinones** [comment]
The underlying issue was that the test was not updated to reflect the updated api endpoint

**Review by freearhey — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
