### PR TITLE
sky.de

### PR DESCRIPTION
**Pull request by RevGear**
Added channels and config for sky.de

Hopefully it's all correct

### CODE REVIEW

**Comment by freearhey** [comment]
Unfortunately, there are several errors in the code.

```sh
➜  epg git:(patch-1) npm test -- sky.de

> test
> npx jest --runInBand "sky.de"

 FAIL  sites/sky.de/sky.de.test.js
  ✕ can generate valid url (1 ms)
  ✕ can parse response (1 ms)
  ✓ can handle empty guide (2 ms)

  ● can generate valid url

    TypeError: url is not a function

      14 |
      15 | it('can generate valid url', () => {
    > 16 |     expect(url()).toBe('https://www.sky.de/sgtvg/service/getBroadcastsForGrid')
         |            ^
      17 | })
      18 |
      19 | it('can parse response', () => {

      at Object.<anonymous> (sites/sky.de/sky.de.test.js:16:12)

  ● can parse response

    TypeError: p.start.toJSON is not a function

      19 | it('can parse response', () => {
      20 |     const result = parser({ content, channel  }).map(p => {
    > 21 |         p.start = p.start.toJSON()
         |                           ^
      22 |         p.stop = p.stop.toJSON()
      23 |         return p
      24 |     })

      at map (sites/sky.de/sky.de.test.js:21:27)
          at Array.map (<anonymous>)
      at Object.<anonymous> (sites/sky.de/sky.de.test.js:20:50)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        0.676 s
```

**Review by freearhey — CHANGES_REQUESTED** [review]
Unfortunately, there are several errors in the code.

```sh
➜  epg git:(patch-1) npm test -- sky.de

> test
> npx jest --runInBand "sky.de"

 FAIL  sites/sky.de/sky.de.test.js
  ✕ can generate valid url (1 ms)
  ✕ can parse response (1 ms)
  ✓ can handle empty guide (2 ms)

  ● can generate valid url

    TypeError: url is not a function

      14 |
      15 | it('can generate valid url', () => {
    > 16 |     expect(url()).toBe('https://www.sky.de/sgtvg/service/getBroadcastsForGrid')
         |            ^
      17 | })
      18 |
      19 | it('can parse response', () => {

      at Object.<anonymous> (sites/sky.de/sky.de.test.js:16:12)

  ● can parse response

    TypeError: p.start.toJSON is not a function

      19 | it('can parse response', () => {
      20 |     const result = parser({ content, channel  }).map(p => {
    > 21 |         p.start = p.start.toJSON()
         |                           ^
      22 |         p.stop = p.stop.toJSON()
      23 |         return p
      24 |     })

      at map (sites/sky.de/sky.de.test.js:21:27)
          at Array.map (<anonymous>)
      at Object.<anonymous> (sites/sky.de/sky.de.test.js:20:50)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        0.676 s
```

**Review by freearhey — CHANGES_REQUESTED** [review]
One test still fails:

```sh
➜  epg git:(pr/547) npm test -- sky.de       

> test
> npx jest --runInBand "sky.de"

 FAIL  sites/sky.de/sky.de.test.js
  ✓ can generate valid url (2 ms)
  ✕ can parse response (3 ms)
  ✓ can handle empty guide (2 ms)

  ● can parse response

    TypeError: p.start.toJSON is not a function

      19 | it('can parse response', () => {
      20 |     const result = parser({ content, channel  }).map(p => {
    > 21 |         p.start = p.start.toJSON()
         |                           ^
      22 |         p.stop = p.stop.toJSON()
      23 |         return p
      24 |     })

      at map (sites/sky.de/sky.de.test.js:21:27)
          at Array.map (<anonymous>)
      at Object.<anonymous> (sites/sky.de/sky.de.test.js:20:50)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        0.66 s, estimated 1 s
```

For the error to go away, the `start` and `stop` properties must return a `dayjs` object instead of timestamp. Try to replace `dayjs.valueOf(item.bsdt)` with `dayjs(item.bsdt)`.

Also you can rewrite the test and compare timestamps instead.

And to make sure that everything works you can run the test yourself with the command:

```sh
npm test -- sky.de
```

**Comment by RevGear** [comment]
Thanks. I'll have a go at fixing these later.

**Pull request merged**
