### PR TITLE
add transvision.co.id

### PR DESCRIPTION
**Pull request by liimee**
add EPG from transvision.co.id

sorry if there's anything I missed 🙏

### CODE REVIEW

**Comment by liimee** [comment]
I'm not sure about those 2 channels − sorry

**Comment by freearhey** [comment]
Russia Today: `RTNews.ru`
T-Music: `TMusic.id`

**Comment by liimee** [comment]
should be ready?

**Comment by freearhey** [comment]
Unfortunately, your request does not include a file with tests, and without it I can not quickly check that everything works and add the site right now to the list. But as soon as I have free time I will definitely check your code.

**Review by freearhey — CHANGES_REQUESTED** [review]
I added a test, and unfortunately it does not pass:

```sh
npx jest --runInBand "transvision.co.id"

 FAIL  sites/transvision.co.id/transvision.co.id.test.js
  ✓ can generate valid url (3 ms)
  ✓ can generate valid request method
  ✓ can generate valid request headers (2 ms)
  ✓ can generate valid request data (10 ms)
  ✕ can parse response (98 ms)
  ✓ can handle empty guide (2 ms)
```

the main problem: the wrong definition of the duration of programs

for example, the parser does not take into account the time zone or the fact that the program can go less than one hour

also, the original program contains duplicate records:
image
this also causes the parser to produce the wrong result

you can run the test on your own with a command:

```sh
npm test -- transvision.co.id
```

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Fixed.

**Comment by liimee** [comment]
sorry for the late response, thanks

**Pull request merged**
