### PR TITLE
Added more channels to tvpassport.com

### PR DESCRIPTION
**Pull request by ajanes3**
Added several Baltimore channels.
Updated WBALDT1.us description

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Comment by ajanes3** [comment]
Resolves #1684

**Comment by ajanes3** [comment]
Resolves #1702

**Comment by ajanes3** [comment]
Cleaned up spacing on the file to make it consistent.

**Comment by ajanes3** [comment]
Sorry, I just realized this is creating new GitHub actions every time I commit. I will change my settings to stop committing to master so often.

**Review by DerpyMcDonuts — APPROVED** [review]
Thank you for repairing the formatting!

**Comment by ajanes3** [comment]
Ok, I am gonna stop, and just limit myself to 1 a day. My urge to fidget with my keyboard is high right now. 👍

**Review by freearhey — APPROVED** [review]

**Review by DerpyMcDonuts — APPROVED** [review]

**Review by DerpyMcDonuts — APPROVED** [review]

**Comment by ajanes3** [comment]
Sorry, had to fix merge conflicts.

**Review by freearhey — APPROVED** [review]

**Review by LaneSh4d0w — APPROVED** [review]

**Pull request merged**
