### PR TITLE
[Rewrite/Fix] pickx.be

### LINKED ISSUE #2506: pickx.be
### Site

pickx.be

### Description

```sh
sites/pickx.be/pickx.be.test.js (10.164 s)
  ● can generate valid url

    thrown: "Exceeded timeout of 10000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      14 | }
      15 |
    > 16 | it('can generate valid url', async () => {
         | ^
      17 |   await fetchApiVersion()
      18 |   const generatedUrl = await url({ channel, date })
      19 |   const resolvedApiVersion = apiVersion()

      at Object.<anonymous> (sites/pickx.be/pickx.be.test.js:16:1)
```

One solution might be to mock a `fetchApiVersion` request in the test.

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Reflect new API change, by modifying both the config and tests.

Added mocking of the API version.

Tests : 

```
TestRun "[epg] run tests: orta.vscode-jest:TestProvider:epg:4 (0)" started
 PASS  sites/pickx.be/pickx.be.test.js
  ✓ can generate valid url (3 ms)
  ✓ can generate valid request headers (1 ms)
  ✓ can parse response (13 ms)
  ✓ can handle empty guide

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.826 s
Ran all test suites matching /\/workspaces\/epg\/sites\/pickx\.be\/pickx\.be\.test\.js/i.
```

Programs : 
```
@BellezaEmporium ➜ /workspaces/epg (freearhey-patch1) $ npm run grab --- --site=pickx.be

> grab
> npx tsx scripts/commands/epg/grab.ts --site=pickx.be

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: pickx.be
loading channels...
  found 378 channel(s)
run #1:
  [1/736] pickx.be (de) - BRFernsehenNord.de - Dec 17, 2024 (53 programs)
  [2/736] pickx.be (de) - BRFernsehenNord.de - Dec 18, 2024 (52 programs)
  [3/736] pickx.be (de) - BRFernsehenNord.de - Dec 18, 2024 (52 programs)
  [4/736] pickx.be (de) - DasErste.de - Dec 18, 2024 (71 programs)
  [5/736] pickx.be (de) - ZDF.de - Dec 18, 2024 (63 programs)
  [6/736] pickx.be (en) - BBCTwo.uk - Dec 18, 2024 (46 programs)
  [7/736] pickx.be (fr) - AB3.be - Dec 18, 2024 (61 programs)
  [8/736] pickx.be (fr) - CinePlusClassicBelgium.be - Dec 18, 2024 (29 programs)
  [9/736] pickx.be (fr) - CinePlusClassicBelgium.be - Dec 17, 2024 (31 programs)
  [10/736] pickx.be (fr) - AB3.be - Dec 17, 2024 (62 programs)
  [11/736] pickx.be (fr) - CartoonNetwork.fr - Dec 18, 2024 (211 programs)
  [12/736] pickx.be (fr) - CartoonNetwork.fr - Dec 17, 2024 (213 programs)
  [13/736] pickx.be (en) - BBCTwo.uk - Dec 17, 2024 (51 programs)
  [14/736] pickx.be (fr) - 13emeRue.fr - Dec 18, 2024 (35 programs)
  [15/736] pickx.be (fr) - CanalZoom.be - Dec 18, 2024 (171 programs)
  [16/736] pickx.be (fr) - CanalZoom.be - Dec 17, 2024 (155 programs)
  [17/736] pickx.be (fr) - 13emeRue.fr - Dec 17, 2024 (40 programs)
  [18/736] pickx.be (fr) - CanalZoom.be - Dec 18, 2024 (171 programs)
  [19/736] pickx.be (fr) - CanalZoom.be - Dec 17, 2024 (155 programs)
  [20/736] pickx.be (de) - ZDF.de - Dec 17, 2024 (61 programs)
  [21/736] pickx.be (en) - BBCOne.uk - Dec 18, 2024 (49 programs)
```

Close #2506

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
My codespace seems to return the same guide over and over (with duplicate programs).

Please check and see if there's duplicate programs on your side, as I should normally have filtered them.

**Review by freearhey — CHANGES_REQUESTED** [review]
Unfortunately in this case it is not enough, the error has not disappeared, it just appears differently:

```sh
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

The point is that even if you manually set `apiVersion` before running the test, this part of the code:

```js
;(async () => {
  try {
    await fetchApiVersion()
    isApiVersionFetched = true
  } catch (error) {
    console.error('Error during script initialization:', error)
  }
})()
```

will still run and the real request will be sent.

**Comment by BellezaEmporium** [comment]
> Unfortunately in this case it is not enough, the error has not disappeared, it just appears differently:
> 
> ```shell
> Jest did not exit one second after the test run has completed.
> 
> 'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
> ```
> 
> The point is that even if you manually set `apiVersion` before running the test, this part of the code:
> 
> ```js
> ;(async () => {
>   try {
>     await fetchApiVersion()
>     isApiVersionFetched = true
>   } catch (error) {
>     console.error('Error during script initialization:', error)
>   }
> })()
> ```
> 
> will still run and the real request will be sent.

That part of the code is now removed, and all tests are passing without an hassle on my side. Did a second test for PickX's EPG, which gives me a 35 (!) Mb file, with little to no dupes. (There's the HD and SD version of the channels registered... that brings up confusion).

**Comment by BellezaEmporium** [comment]
#2520.

**Pull request closed without merging**
