### PR TITLE
epg_tvtv.us : update channels

### PR DESCRIPTION
**Pull request by LaneSh4d0w**
Fills up channel request for San Francisco GovTV.

Close https://github.com/iptv-org/epg/issues/748

### CODE REVIEW

**Review by Gotrees — DISMISSED** [review]
Wanted to wait to see if someone else would check this. Looks good to me though

**Comment by mcastellaneta** [comment]
@Gotrees If it is a newly added channel, I think you should also open a pull request to add it to the /database/data/channels.csv file.

**Review by what-a — DISMISSED** [review]

**Comment by LaneSh4d0w** [comment]
@freearhey I don't understand why there's a "wrong XML ID" issue. I tried 2 ways : full name and tvtv call sign, nothing works.

**Comment by Gotrees** [comment]
@LaneSh4d0w it looks like it needs to be added to the csv file [here](https://github.com/iptv-org/database)?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w it looks like it needs to be added to the csv file [here](https://github.com/iptv-org/database)?

Ah, yes, forgot that...

**Review by freearhey — APPROVED** [review]

**Pull request merged**
