### PR TITLE
Update tvpassport.com.channels.xml

### PR DESCRIPTION
**Pull request by Arkina1234**

### CODE REVIEW

**Comment by PopeyeTheSai10r** [comment]
Hey @Arkina1234, Your first commit changed the whole file. You will need to remove it or close this PR and create a new one.

The second commit looks right.

**Review by Arkina1234 — COMMENTED** [review]
Add xmltv and site id

**Comment by BellezaEmporium** [comment]
99% sure it's linked to a CRLF change.

**Comment by BellezaEmporium** [comment]
Good to go, please review.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
