### PR TITLE
Update web.magentatv.de.config.js

### LINKED ISSUE #2282: osn.com is broken
### Site

osn.com

### Description

when i run the script for osn.com in english and arabic i get a error code 500, might be because its geo-blocked but it looks like this: 
npm run grab -- --site=osn.com --lang=ar

> grab
> npx tsx scripts/commands/epg/grab.ts --site=osn.com --lang=ar

staring...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: osn.com
  lang: ar
loading channels...
  found 101 channel(s)
run #1:
  [1/202] osn.com (ar) - AksyonTVInternational.ph - Dec 16, 2023 (0 programs)
    ERR: Request failed with status code 500
  [2/202] osn.com (ar) - AksyonTVInternational.ph - Dec 17, 2023 (0 programs)
    ERR: Request failed with status code 500
  [3/202] osn.com (ar) - TLCArabia.us - Dec 17, 2023 (0 programs)
    ERR: Request failed with status code 500
  [4/202] osn.com (ar) - TLCArabia.us - Dec 16, 2023 (0 programs)
    ERR: Request failed with status code 500

### LINKED ISSUE #2358: osn
### Site

osn.com

### Description

it says 
osn.com (ar) - BBC Arabic - Apr 20, 2024 (0 programs)
    ERR: unable to verify the first certificate

### LINKED ISSUE #2367: magentatv.de Broken
### Site

web.magentatv.de

### Description

npm run grab -- --site=tv.magenta.at	

FetchError: request to https://api.prod.sngtv.magentatv.de/EPG/JSON/Authenticate?SID=firstup&T=Windows_chrome_118 failed, reason: getaddrinfo EAI_AGAIN api.prod.sngtv.magentatv.de
    at ClientRequest.<anonymous> (/epg/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
  
  So far its only seems to be the .DE Site , the AT ones worked fine while testing .
  
  https://api.prod.sngtv.magentatv.de/EPG/JSON/PlayBillList
  also reports 
  { 
	"retcode":"-3", 
	"desc":"User's session has been expired, please relogin EPG.",
	"errorCode":"85983527" 
}

### PR DESCRIPTION
**Pull request by PopeyeTheSai10r**
Fixes #2367

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
As for web.magenta.de https://api.prod.sngtv.magentatv.de/EPG/JSON/Login?&T=Windows_firefox_127 can give the best EPG server available for your host.

``{"enctytoken":"*random*","encryptiontype":"0002","platformcode":"0200","epgurl":"http://api.prod.sngtv.magentatv.de:33220","version":"MEM V200R008C18SPC806B002","epghttpsurl":"https://api.prod.sngtv.magentatv.de:33227","rootCerAddr":"http://api.prod.sngtv.magentatv.de:33220/EPG/CA/iptv_ca.der","upgAddr4IPTV":"https://slbedifk11100.prod.sngtv.t-online.de:33428/EDS/jsp/upgrade.jsp","upgAddr4OTT":"https://slbedmfk11100.prod.sngtv.t-online.de:33428/EDS/jsp/upgrade.jsp,https://slbedmfk11100.prod.sngtv.t-online.de:33428/EDS/jsp/upgrade.jsp","EPGDomainNameList":[{"key":"2","value":"appepmfk10045.prod.sngtv.t-online.de"},{"key":"3","value":"80.157.246.168"},{"key":"4","value":"80.157.246.168"},{"key":"5","value":"80.157.246.168"},{"key":"6","value":"80.157.246.168"},{"key":"7","value":"80.157.246.168"}],"sam3Para":[{"key":"SAM3ServiceURL","value":"https://accounts.login.idm.telekom.com"},{"key":"OAuthScope","value":"ngtvepg"}]}``

On EPGDomainNameList, you have 2 diff domains.

AUTH is 
``https://api.prod.sngtv.magentatv.de/EPG/JSON/Authenticate?SID=firstup&T=Windows_firefox_127 with {"terminalid":"00:00:00:00:00:00","mac":"00:00:00:00:00:00","terminaltype":"WEBTV","utcEnable":1,"timezone":"Africa/Ceuta","userType":3,"terminalvendor":"Unknown","preSharedKeyID":"PC01P00002","cnonce":"753adeceff416ad53da6be620722bc65"}``

https://api.prod.sngtv.magentatv.de/EPG/JSON/AllChannel?SID=first&T=Windows_firefox_127 gives all channels.

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```sh
npm test -- osn.com   

> test
> run-script-os osn.com


> test:default
> TZ=Pacific/Nauru npx jest --runInBand osn.com

 FAIL  sites/osn.com/osn.com.test.js
  ✕ can generate valid request headers (10 ms)
  ✓ can generate valid url (3 ms)
  ✓ can parse response (ar) (140 ms)
  ✓ can parse response (en) (1 ms)
  ✓ can handle empty guide

  ● can generate valid request headers

    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Object {
    -   "Referer": "https://www.osn.com/ar-ae/watch/tv-schedule",
    +   "Referer": "https://www.osn.com/ar-sa/watch/tv-schedule",
      }

      14 | it('can generate valid request headers', () => {
      15 |   const result = request.headers({ channel: channelAR, date })
    > 16 |   expect(result).toMatchObject({
         |                  ^
      17 |     Referer: 'https://www.osn.com/ar-ae/watch/tv-schedule'
      18 |   })
      19 | })

      at Object.<anonymous> (sites/osn.com/osn.com.test.js:16:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        3.777 s
Ran all test suites matching /osn.com/i.
```

**Comment by BellezaEmporium** [comment]
> Test failed:
> 
> ```sh
> npm test -- osn.com   
> 
> > test
> > run-script-os osn.com
> 
> 
> > test:default
> > TZ=Pacific/Nauru npx jest --runInBand osn.com
> 
>  FAIL  sites/osn.com/osn.com.test.js
>   ✕ can generate valid request headers (10 ms)
>   ✓ can generate valid url (3 ms)
>   ✓ can parse response (ar) (140 ms)
>   ✓ can parse response (en) (1 ms)
>   ✓ can handle empty guide
> 
>   ● can generate valid request headers
> 
>     expect(received).toMatchObject(expected)
> 
>     - Expected  - 1
>     + Received  + 1
> 
>       Object {
>     -   "Referer": "https://www.osn.com/ar-ae/watch/tv-schedule",
>     +   "Referer": "https://www.osn.com/ar-sa/watch/tv-schedule",
>       }
> 
>       14 | it('can generate valid request headers', () => {
>       15 |   const result = request.headers({ channel: channelAR, date })
>     > 16 |   expect(result).toMatchObject({
>          |                  ^
>       17 |     Referer: 'https://www.osn.com/ar-ae/watch/tv-schedule'
>       18 |   })
>       19 | })
> 
>       at Object.<anonymous> (sites/osn.com/osn.com.test.js:16:18)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 4 passed, 5 total
> Snapshots:   0 total
> Time:        3.777 s
> Ran all test suites matching /osn.com/i.
> ```

Your test is concerning osn.com, not magentatv.de

**Review by freearhey — APPROVED** [review]

**Comment by BellezaEmporium** [comment]
Will take a check a bit later, just to make sure I have no issues as well on my side. Though Arhey having an quack on the OSN configuration makes me think we'll have to take a look soon

**Comment by PopeyeTheSai10r** [comment]
> Your test is concerning osn.com, not magentatv.de

The initial PR was for osn and magenta.
osn needs more work, it has been removed from this PR.

> [PopeyeTheSai10r](https://github.com/PopeyeTheSai10r) changed the title ~Update web.magentatv.de.config.js & osn.com.config.js~ Update web.magentatv.de.config.js

**Review by BellezaEmporium — APPROVED** [review]
Tests passed on my codespace. Approved.

**Pull request merged**
