### PR TITLE
tvtv.us re-write

### PR DESCRIPTION
**Pull request by RevGear**
tvtv.us appear to have updated their website so the URL used to get data no longer works This is a re-write using a different URL.

Although the URL does reference New York it appears to work for channels in other regions. I haven't checked the output in detail as there are far too many channels but every channel does include some programmes.

The season/episode/category meta-data is no longer available. All we get are times, program name and optionally a very brief sub-title/description, but that's all we really need.

I haven't as yet found a replacement URL to get a channel listing.

### CODE REVIEW

**Comment by RevGear** [comment]
Forgot to tag the issue #1106

**Comment by spotanjo3** [comment]
What is a new url link please ?

**Comment by nickleby** [comment]
It works to grab the epg schedule, but tv shows description is now missing which is handled in a separate json :/

**Comment by RevGear** [comment]
> It works to grab the epg schedule, but tv shows description is now missing which is handled in a separate json :/

Agreed it's not ideal, but it's better than having nothing. Hopefully it's only a temporary solution.

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
@RevGear Great job, as always!

**Comment by firestickkev** [comment]
Do I need to change original url to get the epg to work. A bit lost to what I need to do. 
Sorry new to this.
Any help appreciated

**Comment by firestickkev** [comment]
Thank you freearhey for you reply

**Comment by moonbairn** [comment]
To all involved.  Thank You!!!

**Comment by spotanjo3** [comment]
Thank you for your hard work. Much appreciated!

**Comment by jamboy3** [comment]
Hi everyone - I didn't want to make a new thread but is this epg down again for anyone else. I just noticed it's back to having no information.

**Comment by spotanjo3** [comment]
> Hi everyone - I didn't want to make a new thread but is this epg down again for anyone else. I just noticed it's back to having no information.

Hi. Not just you. Same here as well. 😏😜

**Pull request merged**
