### PR TITLE
Update vidio.com.channels.xml

### PR DESCRIPTION
**Pull request by deonton1709**

### CODE REVIEW

**Comment by freearhey** [comment]
Why you decided to remove this channel?

**Comment by deonton1709** [comment]
because the channel id is not valid


Pada tanggal Sen, 26 Jul 2021 pukul 08.26 Aleksandr Statciuk <
***@***.***> menulis:

**Comment by freearhey** [comment]
Are you sure? As I see it, the ID of this channel is the same as on the website - 6166. https://www.vidio.com/live/6166-oshop

**Comment by deonton1709** [comment]
because I see the schedule does not appear so I think it is invalid, I'm
sorry

Pada tanggal Sen, 26 Jul 2021 pukul 21.14 Aleksandr Statciuk <
***@***.***> menulis:

**Comment by freearhey** [comment]
I think we can leave the channel on the list in case the program will be added to the site in the future.

**Comment by deonton1709** [comment]
Okay

Pada tanggal Sel, 27 Jul 2021 08.45, Aleksandr Statciuk <
***@***.***> menulis:

**Pull request closed without merging**
