### PR TITLE
add icons to movistar plus

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
This PR adds program icons to the movistar provider

### CODE REVIEW

**Comment by davidclaeysquinones** [comment]
This PR also includes some important fixes for the provider

**Comment by davidclaeysquinones** [comment]
there is still some work to do with the images since the use of the new api

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```sh
npm test -- movistarplus.es  

> test
> run-script-os movistarplus.es


> test:default
> TZ=Pacific/Nauru npx jest --runInBand movistarplus.es

 FAIL  sites/movistarplus.es/movistarplus.es.test.js
  ✕ can generate valid url (9 ms)
  ✕ can parse response (2 ms)
  ✕ can handle empty guide

  ● can generate valid url

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://www.movistarplus.es/programacion-tv/2022-03-11?v=json"
    Received: "https://comunicacion.movistarplus.es/wp-admin/admin-ajax.php"

      13 |
      14 | it('can generate valid url', () => {
    > 15 |   expect(url({ date })).toBe('https://www.movistarplus.es/programacion-tv/2022-03-11?v=json')
         |                         ^
      16 | })
      17 |
      18 | it('can parse response', () => {

      at Object.<anonymous> (sites/movistarplus.es/movistarplus.es.test.js:15:25)

  ● can parse response

    TypeError: Cannot read properties of undefined (reading 'length')

      87 |   const data = json.channelsProgram;
      88 |
    > 89 |   if(data.length != 1)
         |           ^
      90 |     return []
      91 |   return data[0];
      92 | }

      at parseItems (sites/movistarplus.es/movistarplus.es.config.js:89:11)
      at parser (sites/movistarplus.es/movistarplus.es.config.js:30:17)
      at Object.<anonymous> (sites/movistarplus.es/movistarplus.es.test.js:21:18)

  ● can handle empty guide

    TypeError: Cannot read properties of undefined (reading 'length')

      87 |   const data = json.channelsProgram;
      88 |
    > 89 |   if(data.length != 1)
         |           ^
      90 |     return []
      91 |   return data[0];
      92 | }

      at parseItems (sites/movistarplus.es/movistarplus.es.config.js:89:11)
      at parser (sites/movistarplus.es/movistarplus.es.config.js:30:17)
      at Object.<anonymous> (sites/movistarplus.es/movistarplus.es.test.js:49:18)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        3.614 s
Ran all test suites matching /movistarplus.es/i.
```

**Comment by davidclaeysquinones** [comment]
I'm aware that the test currently fails.
The underlying API's had to be changed in order to keep working.
I've had time to rework the code but not the tests.
Since now another API is used the test suite for this provider must be rewritten completely.

**Comment by davidclaeysquinones** [comment]
Update:

Since today they updated the API again and now only empty results are returned.
I'm not sure if this can be solved by adding an extra header or if they really deprecated the API.

I'm aware of another repo that publishes an updated epg for that provider (I'm not going to mention it just in case).
I wonder if maybe we could figure method he's using. Otherwise I'm not sure which options we have left.

**Comment by freearhey** [comment]
The list of providers has been updated in https://github.com/iptv-org/epg/commit/32c32206a0a39ffdc2fa097b0653e4b7a654f424

**Pull request closed without merging**
