### PR TITLE
Update Kan11.org.il to a stable source

### PR DESCRIPTION
**Pull request by ItsKlork**
Kan11.org.il uses cloudflare's protection so scraping is problematic and unstable without libraries such as [cloudscraper](https://www.npmjs.com/package/cloudscraper).
I switched to an alternative source (www.isramedia.net) that lacks icons but provides a much more stable source.

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
If you want to add an alternative source, there is no need to overwrite the old one. You can simply add a new folder `isramedia.net` to the [/sites](https://github.com/iptv-org/epg/tree/master/sites).

**Comment by ItsKlork** [comment]
The current source (The actual Kan11 website) has cloudflare protection and requires usage of libraries such as [`cloudlare-scraper`](https://github.com/JimmyLaurent/cloudflare-scraper) to bypass. This will require switching from axios and I believe it requires creating a fork of `epg-grabber` to support both axios and cloudflare-scraper.
As of now the Kan11.org.il source is practically unusable and almost always returns status code `403`.
The `isramedia.net` source provides a more stable temporary solution until the cloudflare protection problem is solved. I used isramedia to provide the guide for Kan11 so I believe it still fits the current folder (at least until a solution for the Cloudflare protection is found).

**Comment by ItsKlork** [comment]
In addition, the Kan11 website has been updated and requires scraping. The new site also doesn't include the duration/stop time, which seems to be required by the epg-grabber library (Although it actually [isn't required](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L308) by the xmltv format and is normally implied.

**Comment by freearhey** [comment]
Closed due to lack of activity.

**Pull request closed without merging**
