### PR TITLE
Update tvpassport.com.channels.xml

### PR DESCRIPTION
**Pull request by PopeyeTheSai10r**
Added some channels.

### CODE REVIEW

**Review by PopeyeTheSai10r — COMMENTED** [review]
Fixed tvg-id

**Review by RevGear — DISMISSED** [review]

**Review by PopeyeTheSai10r — COMMENTED** [review]
Adding more channels

**Comment by PopeyeTheSai10r** [comment]
squashed all commits into one.

**Review by PopeyeTheSai10r — COMMENTED** [review]
Another one

**Review by RevGear — APPROVED** [review]

**Review by ajanes3 — APPROVED** [review]

**Pull request merged**
