### PR TITLE
Replace the .xml files with the compressed version

### PR DESCRIPTION
**Pull request by freearhey**
Currently, all the guides are published in two versions:

- uncompressed (main one): https://iptv-org.github.io/epg/guides/af/arianaafgtv.com.epg.xml
- compressed: https://iptv-org.github.io/epg/guides/af/arianaafgtv.com.epg.xml.gz

Because of GitHub [restrictions](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#about-size-limits-on-github), we can't upload files larger than 50Mb to GitHub Pages, and the other day the `tvtv.us` guide exceeded that limit: https://github.com/iptv-org/epg/actions/runs/2908910223

To get around the limit and continue to provide guides, we'll have to give up the uncompressed version of the files and only upload `.gz` files to GH Pages.

This update does exactly what: 

- disables the generation of uncompressed files
- replaces all links with new ones

### CODE REVIEW

**Comment by RevGear** [comment]
Any reason for changing the compressed filename from <sitename>.epg.xml.gz to <sitename>.xml.gz? If it was kept the same then anyone already using the compressed files wouldn't need to do anything. This way you are forcing everyone to update their player settings.

**Comment by freearhey** [comment]
I agree, it would be better to keep the old name. I'll redo it now.

**Comment by freearhey** [comment]
Done.

**Review by RevGear — APPROVED** [review]
Looks ok

**Pull request merged**
