### PR TITLE
Fix Canal + Afrique EPG

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Based on the French's Canal +

how it is articulated can be found here : https://hodor.canalplus.pro/api/v2/mycanal/epgGrid/c500bf0e7216fe10b1a6a26a0cd2c278/day/2?channelImageColor=white

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```sh
npm test -- canalplus-afrique.com

> test
> TZ=Pacific/Nauru npx jest --runInBand canalplus-afrique.com

 FAIL  sites/canalplus-afrique.com/canalplus-afrique.com.test.js
  ✕ can generate valid url for today (18 ms)
  ✕ can generate valid url for tomorrow (11 ms)
  ✕ can parse response (10 ms)
  ✓ can handle empty guide (4 ms)

  ● can generate valid url for today

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=0"
    Received: "https://hodor.canalplus.pro/api/v2/mycanal/channels/c500bf0e7216fe10b1a6a26a0cd2c278/80759/broadcasts/day/0"

      19 | it('can generate valid url for today', () => {
      20 |   const date = dayjs.utc().startOf('d')
    > 21 |   expect(url({ channel, date })).toBe(
         |                                  ^
      22 |     'https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=0'
      23 |   )
      24 | })

      at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:21:34)

  ● can generate valid url for tomorrow

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=1"
    Received: "https://hodor.canalplus.pro/api/v2/mycanal/channels/c500bf0e7216fe10b1a6a26a0cd2c278/80759/broadcasts/day/1"

      26 | it('can generate valid url for tomorrow', () => {
      27 |   const date = dayjs.utc().startOf('d').add(1, 'd')
    > 28 |   expect(url({ channel, date })).toBe(
         |                                  ^
      29 |     'https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=1'
      30 |   )
      31 | })

      at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:28:34)

  ● can parse response

    TypeError: personnalities.personnalitiesList is not iterable

      100 |     const personnalities = info.personnalities.find(i => i.prefix == type)
      101 |     if (!personnalities) return people
    > 102 |     for(let person of personnalities.personnalitiesList) {
          |                                      ^
      103 |       people.push(person.title)
      104 |     }
      105 |   }

      at parseCast (sites/canalplus-afrique.com/canalplus-afrique.com.config.js:102:38)
      at parser (sites/canalplus-afrique.com/canalplus-afrique.com.config.js:31:19)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 1 passed, 4 total
Snapshots:   0 total
Time:        0.798 s
Ran all test suites matching /canalplus-afrique.com/i.
```

**Comment by BellezaEmporium** [comment]
> Test failed:
> 
> ```sh
> npm test -- canalplus-afrique.com
> 
> > test
> > TZ=Pacific/Nauru npx jest --runInBand canalplus-afrique.com
> 
>  FAIL  sites/canalplus-afrique.com/canalplus-afrique.com.test.js
>   ✕ can generate valid url for today (18 ms)
>   ✕ can generate valid url for tomorrow (11 ms)
>   ✕ can parse response (10 ms)
>   ✓ can handle empty guide (4 ms)
> 
>   ● can generate valid url for today
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: "https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=0"
>     Received: "https://hodor.canalplus.pro/api/v2/mycanal/channels/c500bf0e7216fe10b1a6a26a0cd2c278/80759/broadcasts/day/0"
> 
>       19 | it('can generate valid url for today', () => {
>       20 |   const date = dayjs.utc().startOf('d')
>     > 21 |   expect(url({ channel, date })).toBe(
>          |                                  ^
>       22 |     'https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=0'
>       23 |   )
>       24 | })
> 
>       at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:21:34)
> 
>   ● can generate valid url for tomorrow
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: "https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=1"
>     Received: "https://hodor.canalplus.pro/api/v2/mycanal/channels/c500bf0e7216fe10b1a6a26a0cd2c278/80759/broadcasts/day/1"
> 
>       26 | it('can generate valid url for tomorrow', () => {
>       27 |   const date = dayjs.utc().startOf('d').add(1, 'd')
>     > 28 |   expect(url({ channel, date })).toBe(
>          |                                  ^
>       29 |     'https://service.canal-overseas.com/ott-frontend/vector/83001/channel/80759/events?filter.day=1'
>       30 |   )
>       31 | })
> 
>       at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:28:34)
> 
>   ● can parse response
> 
>     TypeError: personnalities.personnalitiesList is not iterable
> 
>       100 |     const personnalities = info.personnalities.find(i => i.prefix == type)
>       101 |     if (!personnalities) return people
>     > 102 |     for(let person of personnalities.personnalitiesList) {
>           |                                      ^
>       103 |       people.push(person.title)
>       104 |     }
>       105 |   }
> 
>       at parseCast (sites/canalplus-afrique.com/canalplus-afrique.com.config.js:102:38)
>       at parser (sites/canalplus-afrique.com/canalplus-afrique.com.config.js:31:19)
> 
> Test Suites: 1 failed, 1 total
> Tests:       3 failed, 1 passed, 4 total
> Snapshots:   0 total
> Time:        0.798 s
> Ran all test suites matching /canalplus-afrique.com/i.
> ```

Going to check this.

**Comment by BellezaEmporium** [comment]
Should be fixed.

**Review by freearhey — CHANGES_REQUESTED** [review]
Still gives an error:

```sh
npm test -- canalplus-afrique.com

> test
> TZ=Pacific/Nauru npx jest --runInBand canalplus-afrique.com

 FAIL  sites/canalplus-afrique.com/canalplus-afrique.com.test.js
  ✓ can generate valid url for today (10 ms)
  ✓ can generate valid url for tomorrow (10 ms)
  ✕ can parse response (1 ms)
  ✕ can handle empty guide

  ● can parse response

    ReferenceError: fs is not defined

      32 |
      33 | it('can parse response', done => {
    > 34 |   const content = fs.readFileSync(path.resolve(__dirname, '__data__/content.json'))
         |                   ^
      35 |
      36 |   axios.get.mockImplementation(url => {
      37 |     if (

      at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:34:19)

  ● can handle empty guide

    ReferenceError: fs is not defined

      119 |
      120 | it('can handle empty guide', async () => {
    > 121 |     const content = fs.readFileSync(path.resolve(__dirname, '__data__/no_content.json'))
          |                     ^
      122 |     const result = await parser({ content })
      123 |     expect(result).toMatchObject([])
      124 | })

      at Object.<anonymous> (sites/canalplus-afrique.com/canalplus-afrique.com.test.js:121:21)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        0.582 s, estimated 1 s
Ran all test suites matching /canalplus-afrique.com/i.
```

**Comment by BellezaEmporium** [comment]
Should now be OK. I've forgot to reimport the fs library after my testings. Should be equal to what we have in Canal + France.

**Comment by BellezaEmporium** [comment]
> 

Thanks, going to look at it. Making a few changes linked to the 3 News Now on the database right now, and I take care of this afterwards.

**Pull request closed without merging**
