### PR TITLE
Add guide from nos.pt

### PR DESCRIPTION
**Pull request by freearhey**
#1818

### CODE REVIEW

**Comment by Thermaldude** [comment]
Hello, thks for the work, how put the epg nos.pt in progrmam? Thks

**Review by ajanes3 — APPROVED** [review]
Approved. I'm just going to assume you did this correctly.

@Thermaldude This is still a pull request. You need to wait until it is merged before it will be available.

**Comment by freearhey** [comment]
@ajanes3 I could well be wrong, so please do not approve PR if you are not sure it is error-free.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Comment by Thermaldude** [comment]
> Approved. I'm just going to assume you did this correctly.
> 
> @Thermaldude This is still a pull request. You need to wait until it is merged before it will be available.

Is already pass, but i dont find in epg link, you can help me please? Sorry but i really dont understand how this work, thks

**Comment by PopeyeTheSai10r** [comment]
Hello @Thermaldude, The change was merged 18 hours. You need to allow from 24 to 48 hours after it has been merged to see the new EPG link.

**Pull request merged**
