### PR TITLE
Add UseeTV EPG

### LINKED ISSUE #657: epg addition request for useetv.com
[useetv.com_id.channels.xml.txt](https://github.com/iptv-org/epg/files/8314381/useetv.com_id.channels.xml.txt)

### PR DESCRIPTION
**Pull request by Hans5958**
Here's EPG of all channels on https://www.useetv.com/tv/live, by getting it's schedule from the TV On Demand page (https://www.useetv.com/tvod/metrotv). Even though some channels don't have TVOD, the schedules can still be seen on the page.

It only works for getting today's schedule only, no future schedules.

Resolves #657

### CODE REVIEW

**Comment by Hans5958** [comment]
And I couldn't add the workflow config. Here's the one that I wanted to do.

```yml
name: useetv.com
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [_trigger]
    types:
      - completed
jobs:
  load:
    uses: ./.github/workflows/_load.yml
    with:
      site: ${{github.workflow}}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
```

**Comment by Hans5958** [comment]
Hello, @freearhey. Would it be possible to update the schedule to `0 7 * * *` (00:00 GMT+7)? This website doesn't do future schedules, and having it on `0 0 * * *` (17:00 GMT+7) would mean the today's schedule would only work for the next 7 hours.

**Comment by Hans5958** [comment]
Resolves #657 (Didn't see that issue beforehand lol)

**Comment by freearhey** [comment]
Updated.

**Comment by freearhey** [comment]
Please check `xmltv-id` again (case is also important).

image

**Review by freearhey — APPROVED** [review]

**Pull request merged**
