### PR TITLE
Added TV Natura

### PR DESCRIPTION
**Pull request by Dexer125**

### CODE REVIEW

**Comment by Dexer125** [comment]
Hi, it throws error "The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo." What can I do about it? Rebase?

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Fixed.

**Comment by Dexer125** [comment]
> Fixed.

Can I somehow prevent it for next time?

**Comment by freearhey** [comment]
This was an internal bug, it will be permanently fixed in the next patch.

**Comment by Dexer125** [comment]
> This was an internal bug, it will be permanently fixed in the next patch.

Thank you for information, I thought I am making something wrong.

**Pull request merged**
