### PR TITLE
Update tvtv.us_us-local.channels.xml

### PR DESCRIPTION
**Pull request by PopeyeTheSai10r**
- Added some stations

### CODE REVIEW

**Review by PopeyeTheSai10r — COMMENTED** [review]
Fixed the issue.

**Comment by Gitbone94** [comment]
I'm not sure how to do it, so I hope someone can help. The epg for KAZT-DT2 is not pulling correctly. I'm told it is using stn31303 and that epg shows SIGN OFF in all time periods. I went to tvtv.us and the attached pic shows there is a populated epg for KAZT-DT2 using **stn61548**. If that stn id could be changed I would appreciate it.
KAZT DT2 not CD2
.

**Comment by PopeyeTheSai10r** [comment]
@Gitbone94 I think opening an issue using the 🐞 Bug Report template is the preferred way to get issues like this reported and addressed.

You can open a new issue from [here](https://github.com/iptv-org/epg/issues/new/choose).

**Review by PopeyeTheSai10r — COMMENTED** [review]
Adding one final touch to address issue that was presented in the comment

**Review by PopeyeTheSai10r — COMMENTED** [review]
The check found 1 error which was addressed

**Review by freearhey — APPROVED** [review]

**Comment by Gitbone94** [comment]
Very much appreciated.

**Pull request merged**
