### PR TITLE
Change raiplay.it time to UTC

### PR DESCRIPTION
**Pull request by mcastellaneta**

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
Test failed:

```
npm test -- raiplay.it

 FAIL  sites/raiplay.it/raiplay.it.test.js
  ✓ can generate valid url (19 ms)
  ✕ can parse response (15 ms)
  ✓ can handle empty guide (4 ms)
```

**Comment by mcastellaneta** [comment]
> Test failed:
> 
> ```
> npm test -- raiplay.it
> 
>  FAIL  sites/raiplay.it/raiplay.it.test.js
>   ✓ can generate valid url (19 ms)
>   ✕ can parse response (15 ms)
>   ✓ can handle empty guide (4 ms)
> ```

Could you kindly tell me the type of error? I did the tests and they passed.

**Comment by freearhey** [comment]
The time does not match the time specified in the test:

```
-     "start": "2022-05-03T17:40:00.000Z",
-     "stop": "2022-05-03T18:30:00.000Z",
+     "start": "2022-05-03T16:40:00.000Z",
+     "stop": "2022-05-03T17:30:00.000Z",
```

As you are not getting this error it is most likely a time zone issue.

**Comment by freearhey** [comment]
Unfortunately the time mismatch is still present. I will try to figure out what's wrong later and let you know.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
