### PR TITLE
[Fix] i.mjh.nz

### PR DESCRIPTION
**Pull request by BellezaEmporium**
The epg-parser update might have made the tests act a bit crazy.

- Configuration has been updated
- Tests have been updated.

### CODE REVIEW

**Review by freearhey — APPROVED** [review]

**Comment by PopeyeTheSai10r** [comment]
Test failed for me

```
npm test --- i.mjh.nz

> test
> run-script-os i.mjh.nz


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand i.mjh.nz

 FAIL  sites/i.mjh.nz/i.mjh.nz.test.js (23.16 s)
  √ can generate valid url (12 ms)
  × can parse response (11679 ms)
  √ can handle empty guide (5 ms)

  ● can parse response

    expect(received).toMatchObject(expected)

    - Expected  - 2
    + Received  + 4
```

**Comment by BellezaEmporium** [comment]
> Test failed for me
> 
> ```
> npm test --- i.mjh.nz
> 
> > test
> > run-script-os i.mjh.nz
> 
> 
> > test:win32
> > SET "TZ=Pacific/Nauru" && npx jest --runInBand i.mjh.nz
> 
>  FAIL  sites/i.mjh.nz/i.mjh.nz.test.js (23.16 s)
>   √ can generate valid url (12 ms)
>   × can parse response (11679 ms)
>   √ can handle empty guide (5 ms)
> 
>   ● can parse response
> 
>     expect(received).toMatchObject(expected)
> 
>     - Expected  - 2
>     + Received  + 4
> ```

@PopeyeTheSai10r Could you pull the latest changes added in "master" and "npm ci" ? I believe the new epg-scraper and other bumped dependencies can modify the way the tests are answering.

**Comment by PopeyeTheSai10r** [comment]
Fetched origin, ran "npm ci" and then ran "npm test --- i.mjh.nz"


```
npm ci

> postinstall
> npm run api:load


> api:load
> npx tsx scripts/commands/api/load.ts

channels.json      [====================================] 100.00% | ETA: 0s | 1.7 MB | 1.7 MB/s
countries.json     [====================================] 100.00% | ETA: 0s | 4.3 KB | N/A
regions.json       [====================================] 100.00% | ETA: 0s | 2.2 KB | N/A
subdivisions.json  [====================================] 100.00% | ETA: 0s | 36.6 KB | N/A

added 795 packages, and audited 796 packages in 1m

127 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


npm test --- i.mjh.nz

> test
> run-script-os i.mjh.nz


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand i.mjh.nz

 FAIL  sites/i.mjh.nz/i.mjh.nz.test.js (24.476 s)
  √ can generate valid url (13 ms)
  × can parse response (12279 ms)
  √ can handle empty guide (5 ms)

  ● can parse response

    expect(received).toMatchObject(expected)

    - Expected  - 2
    + Received  + 4

      Object {
        "categories": Array [
          "Movie",
        ],
    -   "date": "20180101",
    +   "date": Array [
    +     "20180101",
    +   ],
        "description": "With her son being held captive by a criminal gang, police officer Amanda Doyle, together with her ex-husband and three unlikely allies, takes part in a desperate plot to hold a wealthy banker and his family to ransom. But this is no ordinary family.",
    -   "icon": "https://provider-static.plex.tv/epg/images/thumbnails/darkmatter-tv-fallback.jpg",
    +   "icon": undefined,
        "start": "2023-06-23T07:14:32.000Z",
        "stop": "2023-06-23T09:09:36.000Z",
        "title": "Killers Within",
      }

      26 |
      27 |   expect(results.length).toBe(11)
    > 28 |   expect(results[0]).toMatchObject({
         |                      ^
      29 |     start: '2023-06-23T07:14:32.000Z',
      30 |     stop: '2023-06-23T09:09:36.000Z',
      31 |     title: 'Killers Within',

      at Object.<anonymous> (sites/i.mjh.nz/i.mjh.nz.test.js:28:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        25.293 s
Ran all test suites matching /i.mjh.nz/i.

```

**Comment by BellezaEmporium** [comment]
> Fetched origin, ran "npm ci" and then ran "npm test --- i.mjh.nz"
> 
> 
> ```
> npm ci
> 
> > postinstall
> > npm run api:load
> 
> 
> > api:load
> > npx tsx scripts/commands/api/load.ts
> 
> channels.json      [====================================] 100.00% | ETA: 0s | 1.7 MB | 1.7 MB/s
> countries.json     [====================================] 100.00% | ETA: 0s | 4.3 KB | N/A
> regions.json       [====================================] 100.00% | ETA: 0s | 2.2 KB | N/A
> subdivisions.json  [====================================] 100.00% | ETA: 0s | 36.6 KB | N/A
> 
> added 795 packages, and audited 796 packages in 1m
> 
> 127 packages are looking for funding
>   run `npm fund` for details
> 
> 1 critical severity vulnerability
> 
> Some issues need review, and may require choosing
> a different dependency.
> 
> Run `npm audit` for details.
> 
> 
> npm test --- i.mjh.nz
> 
> > test
> > run-script-os i.mjh.nz
> 
> 
> > test:win32
> > SET "TZ=Pacific/Nauru" && npx jest --runInBand i.mjh.nz
> 
>  FAIL  sites/i.mjh.nz/i.mjh.nz.test.js (24.476 s)
>   √ can generate valid url (13 ms)
>   × can parse response (12279 ms)
>   √ can handle empty guide (5 ms)
> 
>   ● can parse response
> 
>     expect(received).toMatchObject(expected)
> 
>     - Expected  - 2
>     + Received  + 4
> 
>       Object {
>         "categories": Array [
>           "Movie",
>         ],
>     -   "date": "20180101",
>     +   "date": Array [
>     +     "20180101",
>     +   ],
>         "description": "With her son being held captive by a criminal gang, police officer Amanda Doyle, together with her ex-husband and three unlikely allies, takes part in a desperate plot to hold a wealthy banker and his family to ransom. But this is no ordinary family.",
>     -   "icon": "https://provider-static.plex.tv/epg/images/thumbnails/darkmatter-tv-fallback.jpg",
>     +   "icon": undefined,
>         "start": "2023-06-23T07:14:32.000Z",
>         "stop": "2023-06-23T09:09:36.000Z",
>         "title": "Killers Within",
>       }
> 
>       26 |
>       27 |   expect(results.length).toBe(11)
>     > 28 |   expect(results[0]).toMatchObject({
>          |                      ^
>       29 |     start: '2023-06-23T07:14:32.000Z',
>       30 |     stop: '2023-06-23T09:09:36.000Z',
>       31 |     title: 'Killers Within',
> 
>       at Object.<anonymous> (sites/i.mjh.nz/i.mjh.nz.test.js:28:22)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 2 passed, 3 total
> Snapshots:   0 total
> Time:        25.293 s
> Ran all test suites matching /i.mjh.nz/i.
> 
> ```

Interesting... i'll have to clearly check on my side then.

**Review by freearhey — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
