### PR TITLE
Update nostv.pt.channels.xml with 2 new channels

### PR DESCRIPTION
**Pull request by LITUATUI**
Channel Now and Sport TV 7.

### CODE REVIEW

**Comment by PopeyeTheSai10r** [comment]
`Now.pt` is not a valid TVG-ID

**Comment by LITUATUI** [comment]
> `Now.pt` is not a valid TVG-ID

Why not? It's a new channel, therefore we need to create a new ID for it.

**Comment by PopeyeTheSai10r** [comment]
Take a look at the [Contributing Guide](https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-guide)

> Channel ID from [iptv-org/database](https://github.com/iptv-org/database). A complete list of supported channels can also be found at https://iptv-org.github.io/.

The channel needs to get added to the Database repo first, then we can add the channel to the EPG repo.

**Comment by LITUATUI** [comment]
Thanks for the reply.

I see that the valid ID is [NewsNow.pt](https://iptv-org.github.io/channels/pt/NewsNow) but currently this channel's name is just Now. Maybe we should update the database.

**Review by freearhey — CHANGES_REQUESTED** [review]

**Review by freearhey — APPROVED** [review]

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
