### PR TITLE
Add raiplay.it site

### PR DESCRIPTION
**Pull request by mcastellaneta**

### CODE REVIEW

**Comment by freearhey** [comment]
Could you also add the `raiplay.it/raiplay.it.test.js` file with the tests?

**Comment by mcastellaneta** [comment]
@freearhey Sure, i will ASAP. Let me know if something is wrong with the files of the request, I created them but sincerely i don't know how to test the workflow.

**Comment by freearhey** [comment]
You can run a check on a particular config file by using the command:

```
npm test -- raiplay.it
```

**Comment by mcastellaneta** [comment]
> You can run a check on a particular config file by using the command:
> 
> ```
> npm test -- raiplay.it
> ```

Do I have to clone the whole repository first? Until now, I have created the files from the site. 
I installed epg-grabber to test the result and noticed that the end times are not correct. How can I debug the code?

**Review by freearhey — APPROVED** [review]

**Comment by freearhey** [comment]
Great job!

**Comment by freearhey** [comment]
The guide is already available at this link:

```
https://iptv-org.github.io/epg/guides/it/raiplay.it.epg.xml
```

and tomorrow it should also appear on the homepage.

**Pull request merged**
