### PR TITLE
update pickx provider

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
Pickx.be decided to update the version path.
The url is updated to the new value.
Some effort is needed to study the mechanism that is used in order to generate this url.

### CODE REVIEW

**Comment by bradmurray** [comment]
This patch fixed my inability to pull from this provider.

**Comment by davidclaeysquinones** [comment]
They are employing a new strategy to break this providing.
Now old version url's are still available but when performing queries on those endpoints the returned data is invalid.

**Comment by davidclaeysquinones** [comment]
> This patch fixed my inability to pull from this provider.

They broke the version path again.
I would suggest you use the Telenet.Tv provider with the pending PR I made.

**Comment by davidclaeysquinones** [comment]
When opening the page and letting JS load the url hash can be retrieved through` window.PX_MWC.Config.hashes.`.
I have tried multiple times to see how this config is loaded but I haven't been able to.
My guess is that each time they do an application release the JS code is changed so that there is a different hash.
Another possibility would be that somehow there is a background call to a service or a hidden HTML element containing the hash.

I'm going to keep updating the version paths for now but I understand this is not really manageable.
Hopefully me or someone else is able to figure out how these hashes are generated.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by freearhey — APPROVED** [review]

**Pull request merged**
