### PR TITLE
pickx.be : automatic API URL finding

### PR DESCRIPTION
**Pull request by BellezaEmporium**
Don't ask me how i've found that.

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
Tests have passed, grabber seems to work.

**Comment by BellezaEmporium** [comment]
Summoning @davidclaeysquinones as he was keen into updating the URL all the time.

**Review by freearhey — CHANGES_REQUESTED** [review]
I get a merge conflict when trying to check the branch.

**Review by BellezaEmporium — COMMENTED** [review]
Try now.

**Comment by freearhey** [comment]
Same results:

image

**Comment by BellezaEmporium** [comment]
> Same results:
> 
> image
> 

Hmm... that's really odd. Thing is it was a branch based on master.

**Comment by BellezaEmporium** [comment]
@tohenk may have found the solution. Does it say something now ?

**Comment by freearhey** [comment]
For me, nothing has changed.

**Review by tohenk — APPROVED** [review]
```shell
 npm test -- pickx.be

> test
> run-script-os pickx.be


> test:win32
> SET "TZ=Pacific/Nauru" && npx jest --runInBand pickx.be

 PASS  sites/pickx.be/pickx.be.test.js (11.28 s)
  √ can generate valid url (6297 ms)
  √ can generate valid request headers (3 ms)                                                                                                                     
  √ can parse response (1 ms)                                                                                                                                     
  √ can handle empty guide                                                                                                                                        
                                                                                                                                                                  
Test Suites: 1 passed, 1 total                                                                                                                                    
Tests:       4 passed, 4 total                                                                                                                                    
Snapshots:   0 total
Time:        11.576 s, estimated 22 s
Ran all test suites matching /pickx.be/i.
```

```shell
npm run grab -- --site=pickx.be --lang=en

> grab
> npx tsx scripts/commands/epg/grab.ts --site=pickx.be --lang=en

starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: pickx.be
  lang: en
loading channels...
  found 23 channel(s)
run #1:
  [1/46] pickx.be (en) - NETFLIX - Dec 2, 2024 (17 programs)
  [2/46] pickx.be (en) - NETFLIX - Dec 3, 2024 (17 programs)
  ...
  [45/46] pickx.be (en) - WSport.za - Dec 3, 2024 (41 programs)
  [46/46] pickx.be (en) - PenthouseGold.us - Dec 3, 2024 (29 programs)
  saving to "guide.xml"...
  done in 00h 01m 30s
```

**Review by freearhey — APPROVED** [review]
I guess the mistake was somewhere on my end. Sorry for the inconvenience.

**Pull request merged**
