### PR TITLE
Add guide for Skylink.cz

### PR DESCRIPTION
**Pull request by RevGear**
#1570 

There are a few channels commented out without an xmltv ID, plus many more with a working site ID where I couldn't identify the channel.

The source data includes a picture for many programs but I haven't included this. The URL points to a download script link rather than a jpg file. I don't have a IPTV player that displays the program image so I could test if it would work or not and didn't want to risk it.

### CODE REVIEW

**Comment by m1k1o** [comment]
[Czech MTV was replaced](https://en.wikipedia.org/wiki/MTV_(Czech_TV_channel)) by MTV Global, so looks like MTV Europe CZ should be `MTVGlobal.uk`.

**Comment by m1k1o** [comment]
Corrections I found:

`AXNAdria.us` -> `AXNEurope.gr`
`MarkizaInternational.sk` -> `Markiza.sk`

**Comment by m1k1o** [comment]
Here are following I could identify:

```
11 -> AnimalPlanetCzechRepublic.cz (Animal Planet)
12 -> DiscoveryChannelCzechRepublic.cz (Discovery Channel)
21 -> NationalGeographicCzechRepublic.cz (National Geographic)
37 -> TVP1.pl (TVP 1)
38 -> TVP2.pl (TVP 2)
39 -> Polsat.pl (Polsat)
98 -> DiscoveryScienceCzechRepublic.cz (Discovery Science)
105 -> TravelChannelEMEA.uk (Travel Channel)
122 -> France24French.fr (France 24)
141 -> TV5MondeEurope.fr (TV5 Monde)
182 -> MarkizaDoma.sk (TV Doma)
184 -> JOJPlus.sk (JOJ Plus)
185 -> TVJOJ.sk (JOJ)
235 -> DeluxeMusic.de (Deluxe Music)
276 -> TLCPanregional.us (TLC)
329 -> RTDoc.ru (RT Doc)
356 -> M2.hu (M2)
360 -> DunaTV.hu (Duna)
365 -> Rebel.cz (Rebel)
366 -> CoolTV.hu (Cool TV)
367 -> 360TuneBox.nl (360TuneBox)
368 -> CrimePlusInvestigationCEE.uk (Crime & Investigation)
379 -> ArenaSport2.sk (Arena Sport 2)
383 -> MezzoLiveHD.fr (Mezzo Live HD)
384 -> InvestigationDiscoveryEurope.us (Investigation Discovery)
387 -> PrahaTV.cz (Praha TV)
406 -> EnglishClubTV.uk (English Club TV)
495 -> MarkizaInternational.sk (Markíza International)
```

This is full new changed XML, I also corrected some of the channels `lang=` properties.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<site site="skylink.cz">
  <channels>
    <channel lang="en" xmltv_id="360TuneBox.nl" site_id="367">360TuneBox</channel>
    <channel lang="en" xmltv_id="AlJazeeraEnglish.qa" site_id="217">Al Jazeera</channel>
    <channel lang="cs" xmltv_id="AMCCzechRepublic.cz" site_id="394">AMC</channel>
    <channel lang="cs" xmltv_id="AnimalPlanetCzechRepublic.cz" site_id="11">Animal Planet</channel>
    <channel lang="sk" xmltv_id="ArenaSport1.sk" site_id="344">Arena Sport 1 HD</channel>
    <channel lang="sk" xmltv_id="ArenaSport2.sk" site_id="379">Arena Sport 2</channel>
    <channel lang="cs" xmltv_id="AutoMotorundSport.de" site_id="315">Auto Motor Sport HD</channel>
    <channel lang="cs" xmltv_id="AXNBlack.us" site_id="369">AXN Black</channel>
    <channel lang="cs" xmltv_id="AXNEurope.gr" site_id="9">AXN</channel>
    <channel lang="cs" xmltv_id="AXNWhite.us" site_id="370">AXN White</channel>
    <channel lang="en" xmltv_id="BabyTV.uk" site_id="108">BabyTV</channel>
    <channel lang="cs" xmltv_id="BarrandovPlus.cz" site_id="455">Barrandov Krimi</channel>
    <channel lang="en" xmltv_id="BBCWorldNewsEurope.uk" site_id="97">BBC World News HD</channel>
    <channel lang="en" xmltv_id="BloombergTVEurope.uk" site_id="284">Bloomberg Europe</channel>
    <channel lang="en" xmltv_id="BlueHustler.nl" site_id="146">Blue Hustler</channel>
    <channel lang="en" xmltv_id="BoomerangCEE.us" site_id="73">Boomerang</channel>
    <channel lang="de" xmltv_id="BoomerangEMEA.us" site_id="303">BoomerangEMEA.us</channel>
    <channel lang="en" xmltv_id="BrazzersTVEurope.us" site_id="377">Brazzers TV Europe</channel>
    <channel lang="cs" xmltv_id="CanalPlusDomo.pl" site_id="835">CANAL+ Domo</channel>
    <channel lang="cs" xmltv_id="CartoonNetworkCzechRepublic.cz" site_id="326">Cartoon Network</channel>
    <channel lang="cs" xmltv_id="CBSRealityEMEA.uk" site_id="323">CBS Reality</channel>
    <channel lang="cs" xmltv_id="CinemaxCzechRepublic.cz" site_id="7">Cinemax</channel>
    <channel lang="cs" xmltv_id="Cinemax2CzechRepublic.cz" site_id="112">Cinemax2</channel>
    <channel lang="en" xmltv_id="ClubMTVEurope.uk" site_id="131">Club MTV Europe</channel>
    <channel lang="en" xmltv_id="CNNInternationalEurope.us" site_id="23">CNN International Europe</channel>
    <channel lang="cs" xmltv_id="CNNPrimaNews.cz" site_id="818">CNN Prima NEWS HD</channel>
    <channel lang="hu" xmltv_id="CoolTV.hu" site_id="366">Cool TV</channel>
    <channel lang="cs" xmltv_id="CrimePlusInvestigationCEE.uk" site_id="368">Crime &amp; Investigation</channel>
    <channel lang="cs" xmltv_id="CSFilm.cz" site_id="15">CS Film</channel>
    <channel lang="cs" xmltv_id="CSHistory.cz" site_id="755">CS History</channel>
    <channel lang="cs" xmltv_id="CSHorror.cz" site_id="756">CS Horror</channel>
    <channel lang="cs" xmltv_id="CSMystery.cz" site_id="757">CS Mystery</channel>
    <channel lang="cs" xmltv_id="CTDecko.cz" site_id="357">ČT :D HD</channel>
    <channel lang="cs" xmltv_id="CTart.cz" site_id="358">ČT art HD</channel>
    <channel lang="cs" xmltv_id="CTSport.cz" site_id="18">ČT Sport HD</channel>
    <channel lang="cs" xmltv_id="CT1.cz" site_id="1">ČT1 HD</channel>
    <channel lang="cs" xmltv_id="CT2.cz" site_id="2">ČT2 HD</channel>
    <channel lang="cs" xmltv_id="CT24.cz" site_id="24">ČT24 HD</channel>
    <channel lang="cs" xmltv_id="CT3.cz" site_id="804">ČT3 HD</channel>
    <channel lang="en" xmltv_id="DWEnglish.de" site_id="162">Deutsche Welle English</channel>
    <channel lang="en" xmltv_id="DeluxeMusic.de" site_id="235">Deluxe Music</channel>
    <channel lang="cs" xmltv_id="DiscoveryChannelCzechRepublic.cz" site_id="12">Discovery Channel</channel>
    <channel lang="cs" xmltv_id="DiscoveryScienceCzechRepublic.cz" site_id="98">Discovery Science</channel>
    <channel lang="cs" xmltv_id="DisneyChannelCzechRepublic.cz" site_id="31">Disney Channel</channel>
    <channel lang="en" xmltv_id="DisneyJuniorCzechRepublic.cz" site_id="355">Disney Junior</channel>
    <channel lang="de" xmltv_id="DMAX.de" site_id="151">DMAX</channel>
    <channel lang="en" xmltv_id="DocuBox.nl" site_id="317">DocuBox</channel>
    <channel lang="en" xmltv_id="DorcelTV.nl" site_id="533">Dorcel TV</channel>
    <channel lang="en" xmltv_id="DorcelXXX.nl" site_id="761">Dorcel XXX</channel>
    <channel lang="sk" xmltv_id="DuckTV.sk" site_id="109">ducktv</channel>
    <channel lang="hu" xmltv_id="DunaTV.hu" site_id="360">Duna</channel>
    <channel lang="sk" xmltv_id="Dvojka.sk" site_id="180">Dvojka HD</channel>
    <channel lang="cs" xmltv_id="EEurope.us" site_id="410">E! Europe</channel>
    <channel lang="en" xmltv_id="EnglishClubTV.uk" site_id="406">English Club TV</channel>
    <channel lang="cs" xmltv_id="EpicDrama.se" site_id="601">Epic Drama HD</channel>
    <channel lang="en" xmltv_id="Erox.nl" site_id="300">Erox</channel>
    <channel lang="en" xmltv_id="Eroxxx.nl" site_id="328">Eroxxx</channel>
    <channel lang="en" xmltv_id="EuronewsEnglish.fr" site_id="117">EuroNews</channel>
    <channel lang="cs" xmltv_id="Eurosport1.fr" site_id="16">Eurosport1</channel>
    <channel lang="cs" xmltv_id="Eurosport2.fr" site_id="25">Eurosport2</channel>
    <!-- <channel lang="cs" xmltv_id="Eurosport1.fr" site_id="204">Eurosport 1</channel> -->
    <!-- <channel lang="cs" xmltv_id="Eurosport2.fr" site_id="244">Eurosport 2</channel> -->
    <channel lang="en" xmltv_id="ExtremeSportsChannelEurope.nl" site_id="85">Extreme Sports Channel</channel>
    <channel lang="en" xmltv_id="FashionTVEurope.fr" site_id="119">Fashion TV Europe</channel>
    <channel lang="cs" xmltv_id="FashionBox.nl" site_id="338">FashionBox.nl</channel>
    <channel lang="en" xmltv_id="FastFunBox.nl" site_id="404">Fast&amp;FunBox</channel>
    <channel lang="en" xmltv_id="FightBox.nl" site_id="301">FightBox</channel>
    <channel lang="cs" xmltv_id="FilmEurope.cz" site_id="272">Film Europe HD</channel>
    <channel lang="cs" xmltv_id="FilmEuropePlus.cz" site_id="816">Film Europe+ HD</channel>
    <channel lang="cs" xmltv_id="FilmPlus.cz" site_id="63">Film+</channel>
    <channel lang="cs" xmltv_id="FilmBoxCzechRepublicSlovakia.cz" site_id="64">FilmBox</channel>
    <channel lang="cs" xmltv_id="FilmBoxExtraCzechRepublicSlovakia.cz" site_id="121">FilmBox Extra HD</channel>
    <channel lang="cs" xmltv_id="FilmBoxFamily.nl" site_id="271">FilmBox Family</channel>
    <channel lang="cs" xmltv_id="FilmBoxPremiumCzechRepublicSlovakia.cz" site_id="397">FilmBox Premium HD</channel>
    <channel lang="cs" xmltv_id="FilmBoxStarsCzechRepublicSlovakia.cz" site_id="65">FilmBox Stars</channel>
    <channel lang="sk" xmltv_id="FilmBoxPremiumCzechRepublicSlovakia.cz" site_id="449">FilmBoxPremiumCzechRepublicSlovakia.cz</channel>
    <!-- <channel lang="cs" xmltv_id="FilmEurope.cz" site_id="332">FilmEurope.cz</channel> -->
    <channel lang="cs" xmltv_id="TheFishingHuntingChannel.hu" site_id="102">Fishing and Hunting</channel>
    <channel lang="en" xmltv_id="France24English.fr" site_id="396">France 24 HD</channel>
    <channel lang="fr" xmltv_id="France24French.fr" site_id="122">France 24</channel>
    <channel lang="cs" xmltv_id="GolfChannelCzechia.us" site_id="225">Golf Channel</channel>
    <channel lang="cs" xmltv_id="HBOCzechRepublic.cz" site_id="5">HBO</channel>
    <channel lang="cs" xmltv_id="HBO2CzechRepublic.cz" site_id="6">HBO2</channel>
    <channel lang="cs" xmltv_id="HBO3CzechRepublic.cz" site_id="512">HBO3</channel>
    <channel lang="sk" xmltv_id="HBO3CzechRepublic.cz" site_id="525">HBO3</channel>
    <channel lang="cs" xmltv_id="HistoryCzechRepublic.cz" site_id="125">History HD</channel>
    <channel lang="en" xmltv_id="HustlerTVEurope.nl" site_id="72">Hustler</channel>
    <channel lang="cs" xmltv_id="InvestigationDiscoveryEurope.us" site_id="384">Investigation Discovery</channel>
    <channel lang="en" xmltv_id="HustlerHD.nl" site_id="375">Hustler HD</channel>
    <channel lang="sk" xmltv_id="Jednotka.sk" site_id="181">Jednotka HD</channel>
    <channel lang="cs" xmltv_id="JimJamEurope.uk" site_id="77">JimJam</channel>
    <channel lang="cs" xmltv_id="JOJCinema.sk" site_id="460">JOJ Cinema HD</channel>
    <channel lang="sk" xmltv_id="JOJFamily.sk" site_id="532">JOJ Family HD</channel>
    <channel lang="sk" xmltv_id="JOJCinema.sk" site_id="459">JOJCinema.sk</channel>
    <channel lang="sk" xmltv_id="Jojko.sk" site_id="398">Jojko.sk</channel>
    <channel lang="sk" xmltv_id="JOJPlus.sk" site_id="184">JOJ Plus</channel>
    <channel lang="sk" xmltv_id="JOJSport.sk" site_id="924">JOJSport.sk</channel>
    <channel lang="sk" xmltv_id="JOJWAU.sk" site_id="349">JOJWAU.sk</channel>
    <channel lang="cs" xmltv_id="KinoBarrandov.cz" site_id="454">Kino Barrandov</channel>
    <channel lang="cs" xmltv_id="LalaTV.sk" site_id="728">LALA TV</channel>
    <channel lang="cs" xmltv_id="LeoTV.cz" site_id="127">LEO TV</channel>
    <channel lang="en" xmltv_id="LoveNature.ca" site_id="808">Love Nature HD</channel>
    <channel lang="cs" xmltv_id="M2.hu" site_id="356">M2</channel>
    <channel lang="sk" xmltv_id="MarkizaDajto.sk" site_id="308">Markiza Dajto</channel>
    <channel lang="cs" xmltv_id="MarkizaInternational.sk" site_id="495">Markíza International</channel>
    <channel lang="sk" xmltv_id="Markiza.sk" site_id="183">Markíza</channel>
    <channel lang="sk" xmltv_id="MarkizaDoma.sk" site_id="182">TV Doma</channel>
    <channel lang="fr" xmltv_id="Mezzo.fr" site_id="67">Mezzo HD</channel>
    <channel lang="fr" xmltv_id="MezzoLiveHD.fr" site_id="383">Mezzo Live HD</channel>
    <channel lang="cs" xmltv_id="MinimaxCEE.cz" site_id="32">Minimax</channel>
    <channel lang="cs" xmltv_id="MnamTV.cz" site_id="423">Mňam TV</channel>
    <channel lang="cs" xmltv_id="MnauTV.cz" site_id="568">MnauTV.cz</channel>
    <channel lang="en" xmltv_id="MTV00s.uk" site_id="66">MTV 00s</channel>
    <channel lang="en" xmltv_id="MTV80s.uk" site_id="106">MTV 80s</channel>
    <channel lang="en" xmltv_id="MTV90s.uk" site_id="158">MTV 90s</channel>
    <channel lang="cs" xmltv_id="MTVGlobal.uk" site_id="20">MTV</channel>
    <channel lang="en" xmltv_id="MTVHitsEurope.uk" site_id="159">MTVHitsEurope.uk</channel>
    <channel lang="cs" xmltv_id="MTVLive.uk" site_id="232">MTV Live</channel>
    <!-- <channel lang="cs" xmltv_id="???" site_id="296">Náš region TV</channel> -->
    <channel lang="cs" xmltv_id="NationalGeographicCzechRepublic.cz" site_id="21">National Geographic</channel>
    <channel lang="cs" xmltv_id="NationalGeographicCzechRepublic.cz" site_id="214">National Geographic HD</channel>
    <channel lang="cs" xmltv_id="NationalGeographicWildCzechRepublic.cz" site_id="82">National Geographic Wild</channel>
    <channel lang="cs" xmltv_id="NickJrCzechia.cz" site_id="622">Nick Jr Czech</channel>
    <channel lang="cs" xmltv_id="NickelodeonCzechia.cz" site_id="624">Nickelodeon</channel>
    <channel lang="cs" xmltv_id="NicktoonsCzechia.cz" site_id="759">Nicktoons</channel>
    <channel lang="cs" xmltv_id="NovaAction.cz" site_id="558">Nova Action HD</channel>
    <channel lang="cs" xmltv_id="NovaCinema.cz" site_id="78">Nova Cinema HD</channel>
    <channel lang="cs" xmltv_id="NovaFun.cz" site_id="560">Nova Fun HD</channel>
    <channel lang="cs" xmltv_id="NovaGold.cz" site_id="559">Nova Gold</channel>
    <channel lang="cs" xmltv_id="TVNova.cz" site_id="3">Nova HD</channel>
    <channel lang="cs" xmltv_id="NovaInternational.cz" site_id="494">Nova International</channel>
    <channel lang="cs" xmltv_id="NovaLady.cz" site_id="921">Nova Lady</channel>
    <channel lang="cs" xmltv_id="NovaSport1.cz" site_id="17">Nova Sport 1 HD</channel>
    <channel lang="cs" xmltv_id="NovaSport2.cz" site_id="466">Nova Sport 2 HD</channel>
    <channel lang="cs" xmltv_id="NovaSport3.cz" site_id="904">Nova Sport 3</channel>
    <channel lang="cs" xmltv_id="NovaSport4.cz" site_id="905">Nova Sport 4</channel>
    <channel lang="cs" xmltv_id="Ocko.cz" site_id="19">ÓČKO</channel>
    <channel lang="cs" xmltv_id="OckoBlack.cz" site_id="727">ÓČKO BLACK HD</channel>
    <channel lang="cs" xmltv_id="OckoExpres.cz" site_id="371">ÓČKO EXPRES HD</channel>
    <channel lang="cs" xmltv_id="OckoStar.cz" site_id="352">ÓČKO STAR</channel>
    <channel lang="cs" xmltv_id="ParamountNetworkCzechRepublic.cz" site_id="475">Paramount Network</channel>
    <channel lang="en" xmltv_id="PlayboyTVEurope.us" site_id="103">Playboy TV Europe</channel>
    <channel lang="cs" xmltv_id="Polsat.pl" site_id="39">Polsat</channel>
    <channel lang="cs" xmltv_id="PrahaTV.cz" site_id="387">Praha TV</channel>
    <channel lang="cs" xmltv_id="PrimaCool.cz" site_id="92">Prima COOL HD</channel>
    <channel lang="cs" xmltv_id="Prima.cz" site_id="4">Prima HD</channel>
    <channel lang="cs" xmltv_id="PrimaKrimi.cz" site_id="608">Prima KRIMI HD</channel>
    <channel lang="cs" xmltv_id="PrimaLove.cz" site_id="226">Prima LOVE HD</channel>
    <channel lang="cs" xmltv_id="PrimaMax.cz" site_id="474">Prima MAX HD</channel>
    <channel lang="cs" xmltv_id="PrimaShow.cz" site_id="923">Prima Show</channel>
    <channel lang="cs" xmltv_id="PrimaStar.cz" site_id="897">Prima STAR</channel>
    <channel lang="cs" xmltv_id="PrimaZoom.cz" site_id="333">Prima ZOOM HD</channel>
    <channel lang="cs" xmltv_id="PrimaPlus.cz" site_id="556">PrimaPlus.cz</channel>
    <channel lang="en" xmltv_id="PrivateTV.nl" site_id="74">Private TV</channel>
    <channel lang="cs" xmltv_id="Rebel.cz" site_id="365">Rebel</channel>
    <channel lang="cs" xmltv_id="Relax.cz" site_id="314">RELAX</channel>
    <channel lang="cs" xmltv_id="RetroMusicTV.cz" site_id="206">Retro</channel>
    <channel lang="en" xmltv_id="RT.ru" site_id="137">Russia Today</channel>
    <channel lang="en" xmltv_id="RTDoc.ru" site_id="329">RT Doc</channel>
    <channel lang="sk" xmltv_id="Senzi.sk" site_id="364">Senzi</channel>
    <channel lang="en" xmltv_id="SkyNewsInternational.uk" site_id="138">Sky News International</channel>
    <channel lang="cs" xmltv_id="Skylink7.sk" site_id="723">Skylink 7</channel>
    <channel lang="cs" xmltv_id="SlagerOriginal.cz" site_id="389">Šláger Originál</channel>
    <channel lang="cs" xmltv_id="SlagerPremium.cz" site_id="841">Šlágr Premium HD</channel>
    <channel lang="cs" xmltv_id="Spektrum.cz" site_id="10">Spektrum HD</channel>
    <channel lang="cs" xmltv_id="SpektrumHome.cz" site_id="30">Spektrum Home</channel>
    <channel lang="sk" xmltv_id="Spektrum.cz" site_id="451">Spektrum</channel>
    <channel lang="cs" xmltv_id="Sport1.cz" site_id="61">Sport 1 HD</channel>
    <channel lang="cs" xmltv_id="Sport2.cz" site_id="93">Sport 2 HD</channel>
    <channel lang="sk" xmltv_id="Sport.sk" site_id="928">Sport.sk</channel>
    <channel lang="cs" xmltv_id="Sport5.cz" site_id="91">SPORT5</channel>
    <channel lang="en" xmltv_id="StingrayClassica.ca" site_id="233">Stingray Classica HD</channel>
    <channel lang="en" xmltv_id="StingrayCMusic.ca" site_id="110">Stingray CMusic</channel>
    <channel lang="en" xmltv_id="StingrayiConcerts.ca" site_id="234">Stingray iConcerts HD</channel>
    <channel lang="sk" xmltv_id="TA3.sk" site_id="192">TA3 HD</channel>
    <channel lang="cs" xmltv_id="TelevizeSeznam.cz" site_id="606">Televize Seznam</channel>
    <channel lang="cs" xmltv_id="TLCPanregional.us" site_id="276">TLC</channel>
    <channel lang="cs" xmltv_id="TravelChannelEMEA.uk" site_id="105">Travel Channel</channel>
    <channel lang="cs" xmltv_id="Travelxp.in" site_id="582">Travelxp HD</channel>
    <channel lang="fr" xmltv_id="TV5MondeEurope.fr" site_id="141">TV5 Monde</channel>
    <channel lang="cs" xmltv_id="TVBarrandov.cz" site_id="89">TV Barrandov HD</channel>
    <channel lang="sk" xmltv_id="TVJOJ.sk" site_id="185">JOJ</channel>
    <channel lang="sk" xmltv_id="TVLux.sk" site_id="304">TV Lux HD</channel>
    <channel lang="cs" xmltv_id="TVNoe.cz" site_id="75">TV Noe HD</channel>
    <channel lang="cs" xmltv_id="TVP1.pl" site_id="37">TVP 1</channel>
    <channel lang="cs" xmltv_id="TVP2.pl" site_id="38">TVP 2</channel>
    <channel lang="cs" xmltv_id="TVPaprika.cz" site_id="29">TV Paprika</channel>
    <channel lang="sk" xmltv_id="TV8.sk" site_id="268">TV8 HD</channel>
    <channel lang="cs" xmltv_id="UpNetwork.cz" site_id="570">UP NETWORK</channel>
    <!-- <channel lang="cs" xmltv_id="???" site_id="13">Viasat Explore</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="14">Viasat History HD</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="207">Viasat Nature HD</channel> -->
    <channel lang="en" xmltv_id="VixenTV.ca" site_id="892">VIXEN HD</channel>
    <!-- <channel lang="cs" xmltv_id="???" site_id="40">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="41">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="42">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="44">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="45">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="46">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="47">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="48">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="49">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="50">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="51">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="52">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="53">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="54">???</channel> -->
    <!-- <channel lang="en" xmltv_id="???" site_id="95">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="96">???</channel> -->
    <!-- <channel lang="en" xmltv_id="???" site_id="132">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="149">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="152">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="168">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="169">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="170">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="171">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="172">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="174">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="186">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="187">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="189">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="190">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="191">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="194">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="196">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="197">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="198">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="199">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="200">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="201">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="203">???</channel> -->
    <!-- <channel lang="de" xmltv_id="???" site_id="216">???</channel> -->
    <!-- <channel lang="en" xmltv_id="???" site_id="218">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="236">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="238">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="239">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="243">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="245">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="246">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="247">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="249">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="252">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="254">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="259">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="260">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="266">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="269">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="273">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="288">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="305">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="307">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="324">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="354">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="361">???</channel> -->
    <!-- <channel lang="en" xmltv_id="???" site_id="376">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="393">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="395">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="399">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="400">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="401">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="405">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="407">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="408">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="409">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="448">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="471">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="528">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="699">???</channel> -->
    <!-- <channel lang="cs" xmltv_id="???" site_id="902">???</channel> -->
  </channels>
</site>
```

**Comment by m1k1o** [comment]
Additional channels I found, but they need to be matched:


```
40	ORF1
41	ORF2
42	ARD
46	3SAT
47	ARTE
49	RTL
50	RTL2
52	SAT1
53	VOX
54	Kabel1
132	Music Box
149	MTV Europe CZ
152	CNBC Europe
174	PRO7
189	Spectrum
216	ZDF NEO
243	Duna (SK)
259	RTL
288	Canal 24 Horas
307	M1
354	KiKA
361	RTL
376	Ginx eSports TV
393	ZDF
399	HTV1
400	HTV2
408	SAT.1 Gold
471	Food Network
528	Premier Sport
699	Power TV
902	Premier Sport 2
```

**Comment by m1k1o** [comment]
I identified remaining, they are mostly duplicates:

```
44  BR3
45  MDR
48  Sport1 (DE)
51  PRO7
95  Adult Channel
96  AXN Digi
168 ČT HD
169 ORF1
170 ORF2
171 SAT.1
172 Sport1 (DE)
186 AXN
187 Polsat
190 Sport 1 (CZ)
191 Discovery
194 National Geographic
196 Viasat History
197 Viasat Explorer
198 HBO 2
199 HBO
200 FilmBox
201 Film+
203 Cinemax
218 Disney Channel
236 Animal Planet
238 CS Film
239 ČT sport
245 FilmBox Plus
246 FilmBox Extra HD
247 Fishing and Hunting
249 History Channel
252 National Geographic Wild
254 TV Paprika
260 Sport 2
266 Viasat Nature
269 National Geographic Wild HD
273 Duck TV HD
305 TV Liptov
324 CBS Reality
395 AMC
401 TV Central
405 FILMpro
407 V1
409 TV Morava
448 FilmBox Family
```

**Comment by m1k1o** [comment]
Looks good.

This is correct, can be uncommented: 401 TV Central is `TVCentral.sk`.
This is incorrect: 407 TV1.bg is not `TV1.bg`. It is czech regional channel: https://vzpravy.cz/ It is missing in DB, as well with https://www.regionalnitelevize.cz/. I'll be adding them to DB.

**Comment by RevGear** [comment]
@m1k1o Name change to `mujtvprogram.cz` makes much more sense. I found it via the Skylink website and hadn't realised they were using data from another source.

Thanks for all your help. I think I would have still struggled to identify some of the channel even if they were in a language I spoke.

There's a few still with missing IDs, possibly missing from the database. I think we just put it live as it is and then pick off any additions/corrections later.

**Comment by m1k1o** [comment]
Yes, i think we are good to go. I posted latest channels that I identified above. It can go live.

**Review by freearhey — APPROVED** [review]

**Pull request merged**
