### PR TITLE
Patch 2023.01.3

### PR DESCRIPTION
**Pull request by freearhey**
**Changes:**

- added back guides grouped by source+language

image

- ~~if the source has a description in several languages all will be added to the guide (English will always be first in the list).~~

- removed guides grouped by country
  As these couple of days have shown merged guides did create more complexity than convenience (missing channels/inaccurate source/hard to debug). And since most apps allow you to add more than one EPG, people can create their own perfect guide without such combined guides. 

- the number of days for which to download the program can now be specified in the config
  Increasing this value must be done for each site separately to avoid exceeding the limit of either [GitHub Pages](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits) or the source.

```js
module.exports = {
  site: 'allente.se',
  days: 2,
  ...
}
```

- the `days` property has also been added to [api/guides.json](https://github.com/iptv-org/api#guides)

```json
{
    "channel": "KSTSDT3.us",
    "site": "tvtv.us",
    "lang": "en",
    "days": 2,
    "url": "https://iptv-org.github.io/epg/guides/us.xml"
  }
```

Test run: https://github.com/iptv-org/epg/actions/runs/3882491201
Test run result: https://github.com/iptv-org/epg/tree/bot/auto-update-1673346956

### CODE REVIEW

**Comment by F640** [comment]
> if the source has a description in several languages all will be added to the guide (English will always be first in the list)

I just think the language should stay separated like the old one, most IPTV players don't have feature to change guide language.

**Comment by RevGear** [comment]
Are we able to split by a combination of supplier and language? So we end up with 
```
guides/en/elcinema.com.xml
guides/ar/elcinema.com.xml
````
or if you prefer 
```
guides/elcinema.com/en.xml
guides/elcinema.com/ar.xml
````

Most players should be able to handle multiple EPG sources. Gives the end-users maximum flexibility to create a solution that fits their needs.

**Comment by s-digweed** [comment]
> Changes:
> 
> * added back guides grouped by source
> 
> image
> 
> * if the source has a description in several languages all will be added to the guide (English will always be first in the list). Here is how it looks:
> 
> ```
> <programme start="20230109000000 +0000" stop="20230109010000 +0000" channel="AlDafrahTV.ae">
>    <title lang="en">Shaykh El Harah Wa El Garee&apos;a</title>
>    <title lang="ar">شيخ الحارة والجريئة</title>
>    <desc lang="ar">تعود إيناس الدغيدي لإحياء برنامج شيخ الحارة مجددًا، حيث تستضيف مجموعة من الشخصيات البارزة والمشهورة على الساحة، من أجل تسليط الضوء على أسرار كبيرة في حياتهم وشخصياتهم بشكل جريء.</desc>
>    <category lang="en">Program</category>
>    <category lang="ar">ﺑﺮﻧﺎﻣﺞ</category>
>    <icon src="https://media0001.elcinema.com/uploads/_150x200_f0f9fc3c1408146cd659a6eec0f088cbda7738e030e3f11776a770e3998df2c7.jpg"/>
> </programme>
> ```
> 
> * removed guides grouped by country
>   As these couple of days have shown merged guides did create more complexity than convenience (missing channels/inaccurate source/hard to debug). And since most apps allow you to add more than one EPG, people can create their own perfect guide without such combined guides.
> 
> Test run: https://github.com/iptv-org/epg/actions/runs/3871919198 Test run result: https://github.com/iptv-org/epg/tree/bot/auto-update-1673252116

Hello,

I apologize in advance as this is probably not the place to ask but is it possible to have both guides available: complete country guide (pre-merger 3 days ago) and the individual source guide? 

It just gives end-users the extra option and flexibility and would be intensely appreciated.

I will let you guys get back to your awesome work for which we are grateful!!

Thanks!

**Review by PopeyeTheSai10r — APPROVED** [review]

**Comment by PopeyeTheSai10r** [comment]
All looks good.

Having two different version based on language like @RevGear suggested may make things a bit easier.
```
guides/elcinema.com/en.xml
guides/elcinema.com/ar.xml
```

**Review by RevGear — DISMISSED** [review]

**Comment by freearhey** [comment]
@s-digweed I'm sorry, but the answer is no. As I wrote above, maintaining guides grouped by country turned out to be unreasonably difficult. For example, it is not possible to pack more than a 2-day program into such guides simply because not all sources even have a program for more than 2 days. With guides grouped by source+language there should be no such problems as you will be able to pick the guides that suit you.

**Review by RevGear — APPROVED** [review]
The long list of different languages/guides looks a bit overwhelming at first, but I think it's a good solution. I suspect most people aren't going to be interested in more than 2 or 3 different languages so for them the list becomes much more manageable.

Added benefit for the project means that it keeps the files smaller and we don't have to worry about hitting Github's size limits.

I like the idea of moving the number of days into the individual config files.; it gives us a bit more flexibility. Potentially for Australia/Asia sources that are a significant difference ahead of UTC we could move that out to 3 days instead of 2. As things stand now by the time the workflow has finished half the data for the current day is already in the past.

One thing we will need to be careful of when adding new sources/channels is to check the language the data is actual in. I found one recently where every channel in the xml was set as 'nl' as it was using a Dutch site when actually some of the data was French/English/German. I'm sure there will be more to be corrected as/when we spot them.

**Comment by s-digweed** [comment]
> @s-digweed I'm sorry, but the answer is no. As I wrote above, maintaining guides grouped by country turned out to be unreasonably difficult. For example, it is not possible to pack more than a 2-day program into such guides simply because not all sources even have a program for more than 2 days. With guides grouped by source+language there should be no such problems as you will be able to pick the guides that suit you.

I understand.

Would it be possible to keep the current country guides as they are ie instead of attempting to fix them + have the option of source grouping for users who experience issues/havemissing channels from the country guide?

Thanks!

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
