### PR TITLE
Patch 2023.07.2

### LINKED ISSUE #2061: Guide Tv.nu missing programme images
### Description

The downloaded guide from Tv.nu with the following instructions https://github.com/iptv-org/epg does not include programme images /fanart everything else works . Thanks ! Can you please fix the landscape image work again?

### LINKED ISSUE #2094: nmp command gives error message
Gentlemen, 
I am not a programmer nor understand commands as well. In order to get the epg data I need I followed the instructions on my PC, installed the neccessary programs and run the commands as written, but I could not get what I want. The error message I get after the command: SITE=digiturk.com.tr npm run grab is as follows, please help, I do not know what I am doing wrong:
akdem@smailey MINGW64 ~/epg (master)
$ SITE=raiplay.it npm run grab

> grab
> npx epg-grabber --config=sites/${SITE}/${SITE}.config.js --channels=sites/${SITE}/${SITE}.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/${SITE}/${SITE}.config.js'...
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module 'C:\Users\akdem\epg\sites\${SITE}\${SITE}.config.js'
Require stack:
- C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at main (C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js:54:16)
    at Object.<anonymous> (C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\akdem\\epg\\node_modules\\epg-grabber\\bin\\epg-grabber.js'
  ]
}

Node.js v18.16.0

### LINKED ISSUE #2119: GIT bach issue EPG
### Description

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ npm install

up to date, audited 754 packages in 6s

94 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (22 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$ set SITE=beinsports.com&& npm run grab

> grab
> cross-var epg-grabber --config=sites/$SITE/$SITE.config.js --channels=sites/$SITE/$SITE.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/$SITE/$SITE.config.js'...
node:internal/modules/cjs/loader:1072
  const err = new Error(message);
              ^

Error: Cannot find module 'C:\Users\Kareemelmasryy\epg\sites\$SITE\$SITE.config.js'
Require stack:
- C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at main (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:54:16)
    at Object.<anonymous> (C:\Users\Kareemelmasryy\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Kareemelmasryy\\epg\\node_modules\\epg-grabber\\bin\\epg-grabber.js'
  ]
}

Node.js v20.3.1

Kareemelmasry@Kareemlap MINGW64 ~/epg (master)
$

### LINKED ISSUE #2122: Sites that don't respect the `sites/${site}/${site}.channels.xml` pattern fail.
Sites that don't respect the `sites/${site}/${site}.channels.xml` pattern like https://github.com/iptv-org/epg/tree/master/sites/beinsports.com will not work using the `npm run grab` script as some sites have `_{lang}` suffixes.

e.g.
image

Error:
```
Error: ENOENT: no such file or directory, open '/epg/sites/beinsports.com/beinsports.com.channels.xml'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.read (/epg/node_modules/epg-grabber/src/file.js:13:13)
    at main (/epg/node_modules/epg-grabber/bin/epg-grabber.js:77:28)
    at Object.<anonymous> (/epg/node_modules/epg-grabber/bin/epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/epg/sites/beinsports.com/beinsports.com.channels.xml'
}
```

### PR DESCRIPTION
**Pull request by freearhey**
Changes:

- fix: the update should finally resolve the problem with running parsing on Windows (fixes #2119, fixes #2094)
- fix: channel list was not loaded correctly if it was split into several files (fixes #2122)
- feat: channel logos added to the guides (resolves #2061)
- feat: added ability to generate a compressed version of a guide
- feat: added ability to filter guides by language
- feat: downloads of a guide can now be run on a schedule (resolves https://github.com/orgs/iptv-org/discussions/446, resolves https://github.com/orgs/iptv-org/discussions/416)

Run `grab` script:

```sh
npm run grab -- --site=example.com --lang=fr --gzip --cron="*/1 * * * *"
```

Test:

```sh
npm test -- grab
```

### CODE REVIEW

**Comment by YassineElbouchaibi** [comment]
This will prevent passing additional arguments to epg-grabber. Could additional arguments be caught and passed to epg-grabber?

**Comment by freearhey** [comment]
We store all site settings in configs, so there is no need to specify additional arguments. But if you need more fine-tuning you can just use `epg-grabber` directly, like so:

```sh
npx epg-grabber --config=sites/example.com/example.com.config.js --channels=sites/example.com/example.com.channels.xml --output=guides/{lang}/{site}.xml
```

**Review by PopeyeTheSai10r — APPROVED** [review]

**Comment by trincowski** [comment]
@PopeyeTheSai10r What's up with this PR? Why is it taking so long to be approved?

**Comment by trincowski** [comment]
Nice, thanks!

**Comment by BellezaEmporium** [comment]
> Nice, thanks!

As I do not watch this space on a regular basis it can happen sometimes haha. Your email made me check in.

**Pull request merged**
