### PR TITLE
fix get api version

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
The site again changed the way of obtaining the version url.

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
Not a version issue, they've changed the airings URL actually. ("minified-airings")

**Comment by davidclaeysquinones** [comment]
the present url is still working after the changes I proposed

**Comment by BellezaEmporium** [comment]
image
Not on my side.

**Comment by BellezaEmporium** [comment]
image
"minified-airings" (with both your method and mine)

**Comment by davidclaeysquinones** [comment]
Not sure what's going on.
afbeelding

Maybe it has something to do with the region. If minified-airings works better we surely can change it.

**Comment by BellezaEmporium** [comment]
> Not sure what's going on. afbeelding
> 
> Maybe it has something to do with the region. If minified-airings works better we surely can change it.

Well... if it works for you, then it's rather weird for me. Maybe it's a matter of referer/origin, though I had no issues into switching API endpoints.

PickX's API on my side (Website, French-BE) gives me "minified-airings".

**Comment by davidclaeysquinones** [comment]
> > Not sure what's going on. afbeelding
> > Maybe it has something to do with the region. If minified-airings works better we surely can change it.
> 
> Well... if it works for you, then it's rather weird for me. Maybe it's a matter of referer/origin, though I had no issues into switching API endpoints.
> 
> PickX's API on my side (Website, French-BE) gives me "minified-airings".

On my side I also have noticed that they use a different endpoint is used. But the old endpoint is still working.

**Comment by davidclaeysquinones** [comment]
> (and honestly, the "minified-airings" makes it worse, as both airing dates and program data are split inside the JSON)
> 
> Just for the sake of testing, can you tell me if PR #2518 works for you ?

Weirdly enough your PR also works. 
I'm not sure it will work on the long term, because if you look at the current request they use a different mechanism to generate the api version.

**Comment by BellezaEmporium** [comment]
> > (and honestly, the "minified-airings" makes it worse, as both airing dates and program data are split inside the JSON)
> > Just for the sake of testing, can you tell me if PR #2518 works for you ?
> 
> Weirdly enough your PR also works. I'm not sure it will work on the long term, because if you look at the current request they use a different mechanism to generate the api version.

The best of both worlds would be to have both our methods, yours to begin, mine as a fallback.

**Comment by davidclaeysquinones** [comment]
what makes it thing a bit difficult is that instead of returning 404 errors when an url is wrong, they return empty data when returning the programs.

Before I made the changes in my PR a version was correctly retrieved, but when getting the airings invalid data was returned.
So while it's definitely not impossible we have to be smart about this.

**Comment by BellezaEmporium** [comment]
An idea that just got into my attention is that the hashes might be somewhere in their GraphQL API... if we query it, we might get it. It's in the PickX MWC config.

**Comment by BellezaEmporium** [comment]
image
Huh. Now that's odd.

**Comment by davidclaeysquinones** [comment]
> An idea that just got into my attention is that the hashes might be somewhere in their GraphQL API... if we query it, we might get it. It's in the PickX MWC config.

Thats one of the values I parse in order to get the correct versión.
I used your code and modified the regex pattern to that variable. And then there is an endpoint that uses that hash that returns the valid version API.

**Comment by BellezaEmporium** [comment]
OK, found out the issue... it's in the "Accept" headers. If they're removed, the API will refuse to answer.

**Comment by BellezaEmporium** [comment]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br, zstd

Basically, here are the headers I need to make the request work (in Insomnia)

**Comment by davidclaeysquinones** [comment]
> OK, found out the issue... it's in the "Accept" headers. If they're removed, the API will refuse to answer.

The airings API ?

When you go to the Pickx epg site, what's the url that's being used in the ajax requests ?

In my case it looks like this `https://px-epg.azureedge.net/minified-airings/21734497794195v.4.2/2024-12-18/channel/UID50297?timezone=Europe%2FBrussels`.

The reason I bring this up is I thing they might me phasing out endpoints.
So they might have changed the hash mechanism, but they might have a phase out period in order to maintain compatibility
(avoiding caching issues, or waiting until they modify the code on their set-top-boxes).
We might be at a weird time in point where it seems the 'old' is still working, while it's going to break the moment they decide to terminate the phase out.
 
This is all an assumption since this provider is intentionally a PIA.

**Comment by BellezaEmporium** [comment]
For me it looks like this : https://px-epg.azureedge.net/minified-airings/21734516102845v.4.2/2024-12-18/channel/UID50208?timezone=Europe%2FParis

**Comment by davidclaeysquinones** [comment]
If you go to `https://www.pickx.be/api/s-375ce5e452cf964b4158545d9ddf26cc97d6411f0998a2fa7ed5922c88d5bdc4` (PickX MWC config endpoint) the following is returned :
`{"version":"21734497794195v.4.2"}`

That returns the `21734447700399v.4.2` value.

The **REACT_APP_VERSION_HASH** value is `6cf6c50068fe62f1c110f27da0257e3572024018f824c137d379653481d272df`

If you try to retrieve the version through `https://www.pickx.be/api/s-6cf6c50068fe62f1c110f27da0257e3572024018f824c137d379653481d272df` the following is returned :

```
{
    "version": "11702375189765v.4.2"
}
```

This might give the impression it's still somehow working, but the airings endpoint is broken when using this version.

**Comment by davidclaeysquinones** [comment]
> For me it looks like this : https://px-epg.azureedge.net/minified-airings/21734516102845v.4.2/2024-12-18/channel/UID50208?timezone=Europe%2FParis

That seems to match up.

**Comment by BellezaEmporium** [comment]
Interesting...

**Comment by BellezaEmporium** [comment]
Well, great job ! I've remade my tests and code based on yours, and it works pretty fine on my side. Will close my PR and approve yours.

**Comment by davidclaeysquinones** [comment]
> Interesting...

Yeah for some reason that still works for the minified-airings but not on the airings endpoint.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by davidclaeysquinones** [comment]
> Well, great job ! I've remade my tests and code based on yours, and it works pretty fine on my side. Will close my PR and approve yours.

I haven't modified any test on my PR. So if you've remade them you might want to add them.
You want me to add you as a contributor so that you can commit on my branch ?

**Comment by BellezaEmporium** [comment]
Tell me if the new version of the PR still works for you. I've managed to mock the fetchAPIVersion function quite properly it seems. Everything seems to pass.

**Comment by davidclaeysquinones** [comment]
Both the channel retrieval and tests work without issue.
Thanks for the mention in your commit.
I'll close my PR so that the maintainers don't have confusions regarding which one to approve.

**Comment by davidclaeysquinones** [comment]
PR #2519 already contains the proposed fix + additional changes.

**Pull request closed without merging**
