### PR TITLE
Update programetv.ro_ro.channels.xml

### PR DESCRIPTION
**Pull request by benevenstanciano**
Several channels under "Pro TV" have rebranded, currently these are pointing to nothing so I've updated the channel site_id and xmltv_Id and realphabetised. Also added WarnerTV which is the rebranded TNT.

### CODE REVIEW

**Comment by benevenstanciano** [comment]
Pending update to Channels.csv, I'll let you know when I've submitted that

**Comment by benevenstanciano** [comment]
Pending PR: https://github.com/iptv-org/database/pull/112

**Comment by benevenstanciano** [comment]
I messed up with WarnerTV. It should be WarnerTVRomania.ro and not WarnerTV.ro.

**Comment by benevenstanciano** [comment]
Should be fixed now, ready for pull

**Review by freearhey — APPROVED** [review]

**Pull request merged**
